#!/bin/bash

NAMESPACE=${NAMESPACE:-default}

PROG=$(basename "$0")

OPTIONS=""

printhelp()
{
  echo "Usage: $PROG -w workflow [-e EXTERNAL_MGS] [-m] [-n]"
  echo
  echo "  -w WORKFLOW      Resource name of the workflow."
  echo "  -e EXTERNAL_MGS  External MGS to use."
  echo "  -m               Combine MGT/MDT on same block device."
  echo "  -n               Dry run.  Print YAML and exit."
  echo
  exit 2
}

OPTIND=1
while getopts ":hw:e:mn" opt
do
  case $opt in
  w) WORKFLOW=$OPTARG ;;
  e) EXTERNAL_MGS=$OPTARG ;;
  m) COMBINED_MGTMDT=yes ;;
  n) DRYRUN=yes ;;
  *) printhelp ;;
  esac
done
shift $((OPTIND-1))

if [[ -z $WORKFLOW ]]
then
  echo "$PROG: Must specify -w"
  exit 2
fi

if [[ -n $EXTERNAL_MGS && -n $COMBINED_MGTMDT ]]
then
  echo "$PROG: specify only one of -e or -m"
  exit 2
fi

if [[ -n $EXTERNAL_MGS ]]
then
  OPTIONS="$OPTIONS external_mgs=$EXTERNAL_MGS"
fi
if [[ -n $COMBINED_MGTMDT ]]
then
  OPTIONS="$OPTIONS combined_mgtmdt"
fi

# Strip leading and trailing whitespace; add semicolon as separator.
OPTIONS=$(echo "$OPTIONS" | sed -e 's/^ *//' -e 's/ *$//' -e 's/ /;/g')

wfyaml=/tmp/wfyaml.$$
cat > $wfyaml <<EndOfYaml
apiVersion: dws.cray.hpe.com/v1alpha1
kind: Workflow
metadata:
  name: $WORKFLOW
  namespace: $NAMESPACE
spec:
  desiredState: Proposal
  dwDirectives:
  - '#DW jobdw type=lustre $OPTIONS capacity=5GB name=$WORKFLOW'
  jobID: 9000001
  userID: 1001
  groupID: 1001
  wlmID: 5f239bd8-30db-450b-8c2c-a1a7c8631a1a
EndOfYaml

if [[ -n $DRYRUN ]]
then
  cat $wfyaml
  rm -f $wfyaml
  exit 1
fi

echo Attempting to create $WORKFLOW

kubectl apply -f $wfyaml
retCode=$?
rm -f $wfyaml

if [ $retCode -ne 0 ]; then
    echo Create $WORKFLOW failed
    exit $retCode
fi

# Verify the resource was created.
kubectl get -n default workflow "$WORKFLOW"
exit $?
