#!/bin/bash

DWSHOST=${DWSHOST:-localhost}
DWSPORT=${DWSPORT:-8080}
NAMESPACE=${NAMESPACE:-default}

rname=$1
[[ -n $rname ]] || rname="dws$$"

data='{'
data+='  "metadata": {'
data+='    "name": "'$rname'",'
data+='    "namespace": "'$NAMESPACE'"'
data+='  },'
data+='  "kind": "Workflow",'
data+='  "apiVersion": "dws.cray.hpe.com/v1alpha1",'
data+='  "spec": {'
data+='    "desiredState": "proposal",'
data+='    "dwDirectives": ['
data+='      "#DW jobdw type=lustre capacity=5GB name='$rname'"'
data+='    ],'
data+='    "jobID": 9000001,'
data+='    "userID": 1001,'
data+='    "wlmID": "5f239bd8-30db-450b-8c2c-a1a7c8631a1a"'
data+='  }'
data+='}'

echo Attempting to create $rname on "$DWSHOST":"$DWSPORT"
jsondata="$data"

admitResponse=$(curl -s -X POST "http://${DWSHOST}:${DWSPORT}/apis/dws.cray.hpe.com/v1alpha1/namespaces/$NAMESPACE/workflows" -H "Content-Type: application/json" -d "$jsondata")
retCode=$?

# If the curl command failed, then we assume we failed to create the WFR...
if [ $retCode -ne 0 ]; then
    echo Create $rname failed
    exit $retCode
fi

# Verify the resource was created.
kubectl get -n default workflow "$rname"
exit $?
