#!/bin/bash

DWSHOST=${DWSHOST:-localhost}
DWSPORT=${DWSPORT:-8080}
NAMESPACE=${NAMESPACE:-default}
# NAMESPACE=${NAMESPACE:-nnf-system}

rname=$1
[[ -n $rname ]] || rname="dws-workflow-test-$$"

data='{'
data+='  "metadata": {'
data+='    "name": "##RNAME##",'
data+='    "namespace": "##NAMESPACE##"'
data+='  },'
data+='  "kind": "Workflow",'
data+='  "apiVersion": "dws.cray.hpe.com/v1alpha1",'
data+='  "spec": {'
data+='    "desiredState": "proposal",'
data+='    "dwDirectives": ['
data+='      "#DW jobdw type=lustre capacity=10TB name=anthonyMotC0",'
data+='      "#DW jobdw type=lustre capacity=20TB name=anthonyMotC1",'
data+='      "#DW jobdw type=lustre capacity=30TB name=anthonyMotC2"'
data+='    ],'
data+='    "jobID": 9000001,'
data+='    "userID": 1001,'
data+='    "wlmID": "5f239bd8-30db-450b-8c2c-a1a7c8631a1a"'
data+='  }'
data+='}'

echo Attempting to create $rname ...
jsondata=$(echo $data | sed -e s:##RNAME##:$rname:g -e s:##NAMESPACE##:"$NAMESPACE":g)

admitResponse=$(curl -X POST "http://${DWSHOST}:${DWSPORT}/apis/dws.cray.hpe.com/v1alpha1/namespaces/$NAMESPACE/workflows" -H "Content-Type: application/json" -d "$jsondata")
retCode=$?

# If the curl command failed, then we assume we failed to create the WFR...
if [ $retCode -ne 0 ]; then
    echo Create $rname failed
    exit $retCode
fi

# curl command successful, look at the returned JSON to see if we were successful
echo "$admitResponse" | \
jq 'if .kind == "Status"
	then
		"Failed to create: $admitResponse"
	else
		.metadata.name, .
	end, .'
exit $retCode
