#!/bin/bash

NAMESPACE=${NAMESPACE:-default}

PROG=$(basename "$0")

printhelp()
{
  echo "Usage: $PROG -w workflow [-n]"
  echo
  echo "  -w WORKFLOW      Resource name of the workflow."
  echo "  -n               Dry run.  Print YAML and exit."
  echo
  exit 2
}

OPTIND=1
while getopts ":hw:n" opt
do
  case $opt in
  w) WORKFLOW=$OPTARG ;;
  n) DRYRUN=yes ;;
  *) printhelp ;;
  esac
done
shift $((OPTIND-1))

if [[ -z $WORKFLOW ]]
then
  echo "$PROG: Must specify -w"
  exit 2
fi

wfyaml=/tmp/wfyaml.$$
cat > $wfyaml <<EndOfYaml
apiVersion: dws.cray.hpe.com/v1alpha1
kind: Workflow
metadata:
  name: $WORKFLOW
  namespace: $NAMESPACE
spec:
  desiredState: proposal
  dwDirectives:
  - '#DW jobdw type=xfs capacity=5GB name=$WORKFLOW'
  jobID: 9000001
  userID: 1001
  groupID: 1001
  wlmID: 5f239bd8-30db-450b-8c2c-a1a7c8631a1a
EndOfYaml

if [[ -n $DRYRUN ]]
then
  cat $wfyaml
  rm -f $wfyaml
  exit 1
fi

echo Attempting to create $WORKFLOW

kubectl apply -f $wfyaml
retCode=$?
rm -f $wfyaml

if [ $retCode -ne 0 ]; then
    echo Create $WORKFLOW failed
    exit $retCode
fi

# Verify the resource was created.
kubectl get -n default workflow "$WORKFLOW"
exit $?
