apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-manager
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        - name: ENVIRONMENT
          value: "craystack"
