apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-manager
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
          - name: NNF_SUPPLIED_DEVICES
            # A comma-separated list of devices for nnf-ec/ec to use.
            value: /dev/vdb
        volumeMounts:
          - mountPath: /mnt
            name: mnt-dir
            mountPropagation: Bidirectional
          - mountPath: /dev
            name: dev-dir
          - mountPath: /var/run/dbus
            name: dbus-dir
          - mountPath: /usr/sbin
            name: usbin-dir
          - mountPath: /usr/lib64
            name: lib64-dir
      volumes:
        - name: mnt-dir
          hostPath:
            path: /mnt
        - name: dev-dir
          hostPath:
            path: /dev
        - name: dbus-dir
          hostPath:
            path: /var/run/dbus
        - name: usbin-dir
          hostPath:
            path: /usr/sbin
        - name: lib64-dir
          hostPath:
            path: /usr/lib64

