resources:
- ../top

patches:
# Let the node-manager daemonset mount host dirs for lustre tools and libs.
- path: manager_volumes_patch.yaml
# Arguments for the controller manager that are specific to dp0
- path: manager_environment_deploy_patch.yaml
- path: manager_environment_daemonset_patch.yaml
