apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-manager
  namespace: system
spec:
  template:
    spec:
      containers:
        - name: manager
          args:
            - --controller=node
            - --deleteUnknownVolumes
          volumeMounts:
            - mountPath: /mnt
              name: mnt-dir
              mountPropagation: Bidirectional
            - mountPath: /dev
              name: dev-dir
              mountPropagation: HostToContainer
            - mountPath: /run
              name: run-dir
            - mountPath: /var/run/dbus
              name: dbus-dir
            - mountPath: /run/udev
              name: udev-dir
            - mountPath: /lib/udev
              name: libudev-dir
            - mountPath: /usr/bin
              name: ubin-dir
            - mountPath: /usr/sbin
              name: usbin-dir
            - mountPath: /usr/lib
              name: ulib-dir
            - mountPath: /usr/lib64
              name: lib64-dir
            - mountPath: /sys # For inspecting NVMe/PCI devices
              name: sys-dir
              mountPropagation: HostToContainer
            - mountPath: /var/lib
              name: varlib-dir
            - mountPath: /usr/share # for /usr/share/hwdata/pci.ids file, used by nvme list
              name: ushare-dir
            - mountPath: /tmp # For Redfish Resources
              name: tmp-dir
            - mountPath: /etc
              name: etc-dir
      volumes:
        - name: mnt-dir
          hostPath:
            path: /mnt
        - name: dev-dir
          hostPath:
            path: /dev
        - name: run-dir
          hostPath:
            path: /run
        - name: dbus-dir
          hostPath:
            path: /var/run/dbus
        - name: udev-dir
          hostPath:
            path: /run/udev
        - name: libudev-dir
          hostPath:
            path: /lib/udev
        - name: ubin-dir
          hostPath:
            path: /usr/bin
        - name: usbin-dir
          hostPath:
            path: /usr/sbin
        - name: ulib-dir
          hostPath:
            path: /usr/lib
        - name: lib64-dir
          hostPath:
            path: /usr/lib64
        - name: sys-dir
          hostPath:
            path: /sys
        - name: varlib-dir
          hostPath:
            path: /var/lib
        - name: ushare-dir
          hostPath:
            path: /usr/share
        - name: ulibexec-dir
          hostPath:
            path: /usr/libexec
        - name: tmp-dir
          hostPath:
            path: /tmp
        - name: etc-dir
          hostPath:
            path: /etc
        - name: mdadm-dir
          hostPath:
            path: /run/mdadm

