apiVersion: nnf.cray.hpe.com/v1alpha1
kind: NnfStorageProfile
metadata:
  name: placeholder
  namespace: nnf-system
data:
  lustreStorage:
    combinedMgtMdt: false
    # use htx-lustre server
    externalMgs: 10.1.1.113@tcp