apiVersion: nnf.cray.hpe.com/v1alpha2
kind: NnfStorageProfile
metadata:
  name: template
  namespace: nnf-system
data:
  lustreStorage:
    combinedMgtMdt: false
    # use htx-lustre server
    externalMgs: 10.1.1.113@tcp
