
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-nnf-cray-hpe-com-v1alpha1-nnfstorageprofile
  failurePolicy: Fail
  name: vnnfstorageprofile.kb.io
  rules:
  - apiGroups:
    - nnf.cray.hpe.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nnfstorageprofiles
  sideEffects: None
