---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-nnf-cray-hpe-com-v1alpha8-nnfcontainerprofile
  failurePolicy: Fail
  name: vnnfcontainerprofile.kb.io
  rules:
  - apiGroups:
    - nnf.cray.hpe.com
    apiVersions:
    - v1alpha8
    operations:
    - CREATE
    - UPDATE
    resources:
    - nnfcontainerprofiles
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-nnf-cray-hpe-com-v1alpha8-nnfdatamovementprofile
  failurePolicy: Fail
  name: vnnfdatamovementprofile.kb.io
  rules:
  - apiGroups:
    - nnf.cray.hpe.com
    apiVersions:
    - v1alpha8
    operations:
    - CREATE
    - UPDATE
    resources:
    - nnfdatamovementprofiles
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-nnf-cray-hpe-com-v1alpha8-nnfstorageprofile
  failurePolicy: Fail
  name: vnnfstorageprofile.kb.io
  rules:
  - apiGroups:
    - nnf.cray.hpe.com
    apiVersions:
    - v1alpha8
    operations:
    - CREATE
    - UPDATE
    resources:
    - nnfstorageprofiles
  sideEffects: None
