# permissions for end users to edit datamovements.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: datamovement-editor-role
rules:
- apiGroups:
  - nnf.cray.com
  resources:
  - datamovements
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nnf.cray.com
  resources:
  - datamovements/status
  verbs:
  - get
