apiVersion: v1
kind: ServiceAccount
metadata:
  name: fencing-agent
  namespace: system
---
apiVersion: v1
kind: Secret
metadata:
  name: fencing-agent
  namespace: system
  annotations:
    kubernetes.io/service-account.name: fencing-agent
    kubernetes.io/service-account.namespace: system
type: kubernetes.io/service-account-token
