apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fencing-agent-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fencing-agent-role
subjects:
- kind: ServiceAccount
  name: fencing-agent
  namespace: system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fencing-agent-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: fencing-agent-role
subjects:
- kind: ServiceAccount
  name: fencing-agent
  namespace: system
