# permissions for end users to view nnfaccesses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nnfaccess-viewer-role
rules:
- apiGroups:
  - nnf.cray.com
  resources:
  - nnfaccesses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nnf.cray.com
  resources:
  - nnfaccesses/status
  verbs:
  - get
