# permissions for end users to edit nnfcontainerprofiles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nnfcontainerprofile-editor-role
rules:
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfcontainerprofiles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfcontainerprofiles/status
  verbs:
  - get
