# permissions for end users to view nnfcontainerprofiles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nnfcontainerprofile-viewer-role
rules:
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfcontainerprofiles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfcontainerprofiles/status
  verbs:
  - get
