# permissions for end users to edit nnfdatamovementprofiles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nnfdatamovementprofile-editor-role
rules:
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfdatamovementprofiles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfdatamovementprofiles/status
  verbs:
  - get
