# permissions for end users to view nnfdatamovementmanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nnfdatamovementmanager-viewer-role
rules:
  - apiGroups:
      - dm.cray.hpe.com
    resources:
      - nnfdatamovementmanagers
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - dm.cray.hpe.com
    resources:
      - nnfdatamovementmanagers/status
    verbs:
      - get
