# permissions for end users to view nnfdatamovements.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nnfdatamovement-viewer-role
rules:
  - apiGroups:
      - nnf.cray.hpe.com
    resources:
      - nnfdatamovements
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - nnf.cray.hpe.com
    resources:
      - nnfdatamovements/status
    verbs:
      - get
