# permissions for end users to edit nnfdatamovements.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nnfdatamovement-editor-role
rules:
  - apiGroups:
      - nnf.cray.hpe.com
    resources:
      - nnfdatamovements
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - nnf.cray.hpe.com
    resources:
      - nnfdatamovements/status
    verbs:
      - get
