# permissions for end users to edit nnfjobstorageinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nnfjobstorageinstance-editor-role
rules:
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfjobstorageinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfjobstorageinstances/status
  verbs:
  - get
