# permissions for end users to view nnfjobstorageinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nnfjobstorageinstance-viewer-role
rules:
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfjobstorageinstances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfjobstorageinstances/status
  verbs:
  - get
