# permissions for end users to edit nnflustremgts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: nnf-sos
    app.kubernetes.io/managed-by: kustomize
  name: nnflustremgt-editor-role
rules:
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnflustremgts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnflustremgts/status
  verbs:
  - get
