# permissions for end users to view nnfnodeecdata.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nnfnodeecdata-viewer-role
rules:
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfnodeecdata
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfnodeecdata/status
  verbs:
  - get
