# permissions for end users to edit nnfnodeecdata.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nnfnodeecdata-editor-role
rules:
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfnodeecdata
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfnodeecdata/status
  verbs:
  - get
