# permissions for end users to edit nnfportmanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: nnfportmanager-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: nnf-sos
    app.kubernetes.io/part-of: nnf-sos
    app.kubernetes.io/managed-by: kustomize
  name: nnfportmanager-editor-role
rules:
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfportmanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfportmanagers/status
  verbs:
  - get
