# permissions for end users to edit nnfpersistentstorageinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nnfpersistentstorageinstance-editor-role
rules:
- apiGroups:
  - nnf.cray.com
  resources:
  - nnfpersistentstorageinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nnf.cray.com
  resources:
  - nnfpersistentstorageinstances/status
  verbs:
  - get
