# permissions for end users to edit nnfstorageprofiles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nnfstorageprofile-editor-role
rules:
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfstorageprofiles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfstorageprofiles/status
  verbs:
  - get
