# permissions for end users to view nnfstorages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: nnf-sos
    app.kubernetes.io/managed-by: kustomize
  name: nnfstorage-viewer-role
rules:
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfstorages
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfstorages/status
  verbs:
  - get
