# permissions for end users to edit nnfnodestorages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nnfnodestorage-editor-role
rules:
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfnodestorages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfnodestorages/status
  verbs:
  - get
