---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dataworkflowservices.github.io
  resources:
  - clientmounts
  - computes
  - directivebreakdowns
  - persistentstorageinstances
  - servers
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dataworkflowservices.github.io
  resources:
  - clientmounts/finalizers
  - directivebreakdowns/finalizers
  - systemconfigurations/finalizers
  - workflows/finalizers
  verbs:
  - update
- apiGroups:
  - dataworkflowservices.github.io
  resources:
  - clientmounts/status
  - storages/status
  - systemconfigurations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - dataworkflowservices.github.io
  resources:
  - directivebreakdowns/status
  - persistentstorageinstances/status
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dataworkflowservices.github.io
  resources:
  - nnfstorage
  verbs:
  - delete
  - deletecollection
  - get
  - list
  - update
  - watch
- apiGroups:
  - dataworkflowservices.github.io
  resources:
  - servers/finalizers
  - servers/status
  - storages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dataworkflowservices.github.io
  resources:
  - systemconfigurations
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - dataworkflowservices.github.io
  resources:
  - workflows
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubeflow.org
  resources:
  - mpijobs
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lus.cray.hpe.com
  resources:
  - lustrefilesystems
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - directivebreakdowns/status
  - nnfdatamovementmanagers
  - nnfdatamovementmanagers/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfaccesses
  - nnfcontainerprofiles
  - nnfdatamovementprofiles
  - nnfdatamovements
  - nnflustremgts
  - nnfnodeblockstorages
  - nnfnodestorages
  - nnfstorageprofiles
  - nnfstorages
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfaccesses/finalizers
  - nnflustremgts/finalizers
  - nnfnodeblockstorages/finalizers
  - nnfnodeecdata/finalizers
  - nnfnodes/finalizers
  - nnfnodestorages/finalizers
  - nnfportmanagers/finalizers
  - nnfstorages/finalizers
  - nnfsystemstorages/finalizers
  verbs:
  - update
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfaccesses/status
  - nnflustremgts/status
  - nnfnodeblockstorages/status
  - nnfnodeecdata/status
  - nnfnodes/status
  - nnfnodestorages/status
  - nnfportmanagers/status
  - nnfsystemstorages/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfnodeecdata
  - nnfnodes
  - nnfportmanagers
  - nnfsystemstorages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfstorages/status
  verbs:
  - get
  - list
  - patch
  - update
  - watch
