---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - update
- apiGroups:
  - cray.hpe.com
  resources:
  - lustrefilesystems
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dws.cray.hpe.com
  resources:
  - clientmounts
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dws.cray.hpe.com
  resources:
  - clientmounts/finalizers
  verbs:
  - update
- apiGroups:
  - dws.cray.hpe.com
  resources:
  - clientmounts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - dws.cray.hpe.com
  resources:
  - computes
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dws.cray.hpe.com
  resources:
  - directivebreakdowns
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dws.cray.hpe.com
  resources:
  - directivebreakdowns/finalizers
  verbs:
  - update
- apiGroups:
  - dws.cray.hpe.com
  resources:
  - directivebreakdowns/status
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dws.cray.hpe.com
  resources:
  - nnfstorage
  verbs:
  - delete
  - deletecollection
  - get
  - list
  - update
  - watch
- apiGroups:
  - dws.cray.hpe.com
  resources:
  - persistentstorageinstances
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dws.cray.hpe.com
  resources:
  - persistentstorageinstances/status
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dws.cray.hpe.com
  resources:
  - servers
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dws.cray.hpe.com
  resources:
  - servers/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dws.cray.hpe.com
  resources:
  - servers/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dws.cray.hpe.com
  resources:
  - storages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dws.cray.hpe.com
  resources:
  - storages/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - dws.cray.hpe.com
  resources:
  - systemconfigurations
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - dws.cray.hpe.com
  resources:
  - systemconfigurations/finalizers
  verbs:
  - update
- apiGroups:
  - dws.cray.hpe.com
  resources:
  - systemconfigurations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - dws.cray.hpe.com
  resources:
  - workflows
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dws.cray.hpe.com
  resources:
  - workflows/finalizers
  verbs:
  - update
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - directivebreakdowns/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfaccesses
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfaccesses/finalizers
  verbs:
  - update
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfaccesses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfdatamovements
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfnodeecdata
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfnodeecdata/finalizers
  verbs:
  - update
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfnodeecdata/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfnodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfnodes/finalizers
  verbs:
  - update
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfnodes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfnodestorages
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfnodestorages/finalizers
  verbs:
  - update
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfstorageprofiles
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfstorages
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfstorages/finalizers
  verbs:
  - update
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfstorages/status
  verbs:
  - get
  - list
  - patch
  - update
  - watch
