
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - update
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dws.cray.hpe.com
  resources:
  - computes
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dws.cray.hpe.com
  resources:
  - directivebreakdowns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dws.cray.hpe.com
  resources:
  - directivebreakdowns/finalizers
  verbs:
  - update
- apiGroups:
  - dws.cray.hpe.com
  resources:
  - directivebreakdowns/status
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dws.cray.hpe.com
  resources:
  - servers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dws.cray.hpe.com
  resources:
  - storages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dws.cray.hpe.com
  resources:
  - workflows
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dws.cray.hpe.com
  resources:
  - workflows/finalizers
  verbs:
  - update
- apiGroups:
  - nnf.cray.com
  resources:
  - directivebreakdowns/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfnodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfnodes/finalizers
  verbs:
  - update
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfnodes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfnodestorages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfnodestorages/finalizers
  verbs:
  - update
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfstorages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfstorages/finalizers
  verbs:
  - update
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfstorages/status
  verbs:
  - get
  - patch
  - update
