---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - update
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
- apiGroups:
  - dataworkflowservices.github.io
  resources:
  - clientmounts
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dataworkflowservices.github.io
  resources:
  - clientmounts/finalizers
  verbs:
  - update
- apiGroups:
  - dataworkflowservices.github.io
  resources:
  - clientmounts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - dataworkflowservices.github.io
  resources:
  - computes
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dataworkflowservices.github.io
  resources:
  - directivebreakdowns
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dataworkflowservices.github.io
  resources:
  - directivebreakdowns/finalizers
  verbs:
  - update
- apiGroups:
  - dataworkflowservices.github.io
  resources:
  - directivebreakdowns/status
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dataworkflowservices.github.io
  resources:
  - nnfstorage
  verbs:
  - delete
  - deletecollection
  - get
  - list
  - update
  - watch
- apiGroups:
  - dataworkflowservices.github.io
  resources:
  - persistentstorageinstances
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dataworkflowservices.github.io
  resources:
  - persistentstorageinstances/status
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dataworkflowservices.github.io
  resources:
  - servers
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dataworkflowservices.github.io
  resources:
  - servers/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dataworkflowservices.github.io
  resources:
  - servers/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dataworkflowservices.github.io
  resources:
  - storages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dataworkflowservices.github.io
  resources:
  - storages/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - dataworkflowservices.github.io
  resources:
  - systemconfigurations
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - dataworkflowservices.github.io
  resources:
  - systemconfigurations/finalizers
  verbs:
  - update
- apiGroups:
  - dataworkflowservices.github.io
  resources:
  - systemconfigurations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - dataworkflowservices.github.io
  resources:
  - workflows
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dataworkflowservices.github.io
  resources:
  - workflows/finalizers
  verbs:
  - update
- apiGroups:
  - kubeflow.org
  resources:
  - mpijobs
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lus.cray.hpe.com
  resources:
  - lustrefilesystems
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - directivebreakdowns/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfaccesses
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfaccesses/finalizers
  verbs:
  - update
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfaccesses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfcontainerprofiles
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfdatamovementmanagers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfdatamovementmanagers/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfdatamovementprofiles
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfdatamovements
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnflustremgts
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnflustremgts/finalizers
  verbs:
  - update
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnflustremgts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfnodeblockstorages
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfnodeblockstorages/finalizers
  verbs:
  - update
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfnodeblockstorages/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfnodeecdata
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfnodeecdata/finalizers
  verbs:
  - update
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfnodeecdata/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfnodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfnodes/finalizers
  verbs:
  - update
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfnodes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfnodestorages
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfnodestorages/finalizers
  verbs:
  - update
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfnodestorages/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfportmanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfportmanagers/finalizers
  verbs:
  - update
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfportmanagers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfstorageprofiles
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfstorages
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfstorages/finalizers
  verbs:
  - update
- apiGroups:
  - nnf.cray.hpe.com
  resources:
  - nnfstorages/status
  verbs:
  - get
  - list
  - patch
  - update
  - watch
