apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller-manager
  namespace: system
---
apiVersion: v1
kind: Secret
metadata:
  name: controller-manager
  namespace: system
  annotations:
    kubernetes.io/service-account.name: controller-manager
    kubernetes.io/service-account.namespace: system
type: kubernetes.io/service-account-token