//go:build !ignore_autogenerated

/*
 * Copyright 2025 Hewlett Packard Enterprise Development LP
 * Other additional copyright holders may be indicated within.
 *
 * The entirety of this work is licensed under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 *
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha10

import (
	"k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommandVariablesSpec) DeepCopyInto(out *CommandVariablesSpec) {
	*out = *in
	if in.IndexedValues != nil {
		in, out := &in.IndexedValues, &out.IndexedValues
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommandVariablesSpec.
func (in *CommandVariablesSpec) DeepCopy() *CommandVariablesSpec {
	if in == nil {
		return nil
	}
	out := new(CommandVariablesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LustreStorageSpec) DeepCopyInto(out *LustreStorageSpec) {
	*out = *in
	in.LustreComponents.DeepCopyInto(&out.LustreComponents)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LustreStorageSpec.
func (in *LustreStorageSpec) DeepCopy() *LustreStorageSpec {
	if in == nil {
		return nil
	}
	out := new(LustreStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfAccess) DeepCopyInto(out *NnfAccess) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfAccess.
func (in *NnfAccess) DeepCopy() *NnfAccess {
	if in == nil {
		return nil
	}
	out := new(NnfAccess)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NnfAccess) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfAccessList) DeepCopyInto(out *NnfAccessList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NnfAccess, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfAccessList.
func (in *NnfAccessList) DeepCopy() *NnfAccessList {
	if in == nil {
		return nil
	}
	out := new(NnfAccessList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NnfAccessList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfAccessSpec) DeepCopyInto(out *NnfAccessSpec) {
	*out = *in
	out.ClientReference = in.ClientReference
	out.StorageReference = in.StorageReference
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfAccessSpec.
func (in *NnfAccessSpec) DeepCopy() *NnfAccessSpec {
	if in == nil {
		return nil
	}
	out := new(NnfAccessSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfAccessStatus) DeepCopyInto(out *NnfAccessStatus) {
	*out = *in
	in.ResourceError.DeepCopyInto(&out.ResourceError)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfAccessStatus.
func (in *NnfAccessStatus) DeepCopy() *NnfAccessStatus {
	if in == nil {
		return nil
	}
	out := new(NnfAccessStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfContainer) DeepCopyInto(out *NnfContainer) {
	*out = *in
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EnvFrom != nil {
		in, out := &in.EnvFrom, &out.EnvFrom
		*out = make([]v1.EnvFromSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VolumeMounts != nil {
		in, out := &in.VolumeMounts, &out.VolumeMounts
		*out = make([]v1.VolumeMount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RestartPolicy != nil {
		in, out := &in.RestartPolicy, &out.RestartPolicy
		*out = new(v1.ContainerRestartPolicy)
		**out = **in
	}
	if in.LivenessProbe != nil {
		in, out := &in.LivenessProbe, &out.LivenessProbe
		*out = new(v1.Probe)
		(*in).DeepCopyInto(*out)
	}
	if in.ReadinessProbe != nil {
		in, out := &in.ReadinessProbe, &out.ReadinessProbe
		*out = new(v1.Probe)
		(*in).DeepCopyInto(*out)
	}
	if in.StartupProbe != nil {
		in, out := &in.StartupProbe, &out.StartupProbe
		*out = new(v1.Probe)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfContainer.
func (in *NnfContainer) DeepCopy() *NnfContainer {
	if in == nil {
		return nil
	}
	out := new(NnfContainer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfContainerProfile) DeepCopyInto(out *NnfContainerProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Data.DeepCopyInto(&out.Data)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfContainerProfile.
func (in *NnfContainerProfile) DeepCopy() *NnfContainerProfile {
	if in == nil {
		return nil
	}
	out := new(NnfContainerProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NnfContainerProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfContainerProfileData) DeepCopyInto(out *NnfContainerProfileData) {
	*out = *in
	if in.Storages != nil {
		in, out := &in.Storages, &out.Storages
		*out = make([]NnfContainerProfileStorage, len(*in))
		copy(*out, *in)
	}
	if in.PreRunTimeoutSeconds != nil {
		in, out := &in.PreRunTimeoutSeconds, &out.PreRunTimeoutSeconds
		*out = new(int64)
		**out = **in
	}
	if in.PostRunTimeoutSeconds != nil {
		in, out := &in.PostRunTimeoutSeconds, &out.PostRunTimeoutSeconds
		*out = new(int64)
		**out = **in
	}
	if in.UserID != nil {
		in, out := &in.UserID, &out.UserID
		*out = new(uint32)
		**out = **in
	}
	if in.GroupID != nil {
		in, out := &in.GroupID, &out.GroupID
		*out = new(uint32)
		**out = **in
	}
	if in.NnfSpec != nil {
		in, out := &in.NnfSpec, &out.NnfSpec
		*out = new(NnfPodSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.NnfMPISpec != nil {
		in, out := &in.NnfMPISpec, &out.NnfMPISpec
		*out = new(NnfMPISpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfContainerProfileData.
func (in *NnfContainerProfileData) DeepCopy() *NnfContainerProfileData {
	if in == nil {
		return nil
	}
	out := new(NnfContainerProfileData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfContainerProfileList) DeepCopyInto(out *NnfContainerProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NnfContainerProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfContainerProfileList.
func (in *NnfContainerProfileList) DeepCopy() *NnfContainerProfileList {
	if in == nil {
		return nil
	}
	out := new(NnfContainerProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NnfContainerProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfContainerProfileStorage) DeepCopyInto(out *NnfContainerProfileStorage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfContainerProfileStorage.
func (in *NnfContainerProfileStorage) DeepCopy() *NnfContainerProfileStorage {
	if in == nil {
		return nil
	}
	out := new(NnfContainerProfileStorage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfDataMovement) DeepCopyInto(out *NnfDataMovement) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfDataMovement.
func (in *NnfDataMovement) DeepCopy() *NnfDataMovement {
	if in == nil {
		return nil
	}
	out := new(NnfDataMovement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NnfDataMovement) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfDataMovementCommandStatus) DeepCopyInto(out *NnfDataMovementCommandStatus) {
	*out = *in
	out.ElapsedTime = in.ElapsedTime
	if in.ProgressPercentage != nil {
		in, out := &in.ProgressPercentage, &out.ProgressPercentage
		*out = new(int32)
		**out = **in
	}
	in.LastMessageTime.DeepCopyInto(&out.LastMessageTime)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = new(int32)
		**out = **in
	}
	if in.Directories != nil {
		in, out := &in.Directories, &out.Directories
		*out = new(int32)
		**out = **in
	}
	if in.Files != nil {
		in, out := &in.Files, &out.Files
		*out = new(int32)
		**out = **in
	}
	if in.Links != nil {
		in, out := &in.Links, &out.Links
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfDataMovementCommandStatus.
func (in *NnfDataMovementCommandStatus) DeepCopy() *NnfDataMovementCommandStatus {
	if in == nil {
		return nil
	}
	out := new(NnfDataMovementCommandStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfDataMovementConfig) DeepCopyInto(out *NnfDataMovementConfig) {
	*out = *in
	if in.Slots != nil {
		in, out := &in.Slots, &out.Slots
		*out = new(int)
		**out = **in
	}
	if in.MaxSlots != nil {
		in, out := &in.MaxSlots, &out.MaxSlots
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfDataMovementConfig.
func (in *NnfDataMovementConfig) DeepCopy() *NnfDataMovementConfig {
	if in == nil {
		return nil
	}
	out := new(NnfDataMovementConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfDataMovementList) DeepCopyInto(out *NnfDataMovementList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NnfDataMovement, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfDataMovementList.
func (in *NnfDataMovementList) DeepCopy() *NnfDataMovementList {
	if in == nil {
		return nil
	}
	out := new(NnfDataMovementList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NnfDataMovementList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfDataMovementManager) DeepCopyInto(out *NnfDataMovementManager) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfDataMovementManager.
func (in *NnfDataMovementManager) DeepCopy() *NnfDataMovementManager {
	if in == nil {
		return nil
	}
	out := new(NnfDataMovementManager)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NnfDataMovementManager) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfDataMovementManagerList) DeepCopyInto(out *NnfDataMovementManagerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NnfDataMovementManager, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfDataMovementManagerList.
func (in *NnfDataMovementManagerList) DeepCopy() *NnfDataMovementManagerList {
	if in == nil {
		return nil
	}
	out := new(NnfDataMovementManagerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NnfDataMovementManagerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfDataMovementManagerSpec) DeepCopyInto(out *NnfDataMovementManagerSpec) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
	in.PodSpec.DeepCopyInto(&out.PodSpec)
	in.UpdateStrategy.DeepCopyInto(&out.UpdateStrategy)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfDataMovementManagerSpec.
func (in *NnfDataMovementManagerSpec) DeepCopy() *NnfDataMovementManagerSpec {
	if in == nil {
		return nil
	}
	out := new(NnfDataMovementManagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfDataMovementManagerStatus) DeepCopyInto(out *NnfDataMovementManagerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfDataMovementManagerStatus.
func (in *NnfDataMovementManagerStatus) DeepCopy() *NnfDataMovementManagerStatus {
	if in == nil {
		return nil
	}
	out := new(NnfDataMovementManagerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfDataMovementProfile) DeepCopyInto(out *NnfDataMovementProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Data = in.Data
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfDataMovementProfile.
func (in *NnfDataMovementProfile) DeepCopy() *NnfDataMovementProfile {
	if in == nil {
		return nil
	}
	out := new(NnfDataMovementProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NnfDataMovementProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfDataMovementProfileData) DeepCopyInto(out *NnfDataMovementProfileData) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfDataMovementProfileData.
func (in *NnfDataMovementProfileData) DeepCopy() *NnfDataMovementProfileData {
	if in == nil {
		return nil
	}
	out := new(NnfDataMovementProfileData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfDataMovementProfileList) DeepCopyInto(out *NnfDataMovementProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NnfDataMovementProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfDataMovementProfileList.
func (in *NnfDataMovementProfileList) DeepCopy() *NnfDataMovementProfileList {
	if in == nil {
		return nil
	}
	out := new(NnfDataMovementProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NnfDataMovementProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfDataMovementSpec) DeepCopyInto(out *NnfDataMovementSpec) {
	*out = *in
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(NnfDataMovementSpecSourceDestination)
		**out = **in
	}
	if in.Destination != nil {
		in, out := &in.Destination, &out.Destination
		*out = new(NnfDataMovementSpecSourceDestination)
		**out = **in
	}
	out.ProfileReference = in.ProfileReference
	if in.UserConfig != nil {
		in, out := &in.UserConfig, &out.UserConfig
		*out = new(NnfDataMovementConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfDataMovementSpec.
func (in *NnfDataMovementSpec) DeepCopy() *NnfDataMovementSpec {
	if in == nil {
		return nil
	}
	out := new(NnfDataMovementSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfDataMovementSpecSourceDestination) DeepCopyInto(out *NnfDataMovementSpecSourceDestination) {
	*out = *in
	out.StorageReference = in.StorageReference
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfDataMovementSpecSourceDestination.
func (in *NnfDataMovementSpecSourceDestination) DeepCopy() *NnfDataMovementSpecSourceDestination {
	if in == nil {
		return nil
	}
	out := new(NnfDataMovementSpecSourceDestination)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfDataMovementStatus) DeepCopyInto(out *NnfDataMovementStatus) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.EndTime != nil {
		in, out := &in.EndTime, &out.EndTime
		*out = (*in).DeepCopy()
	}
	if in.CommandStatus != nil {
		in, out := &in.CommandStatus, &out.CommandStatus
		*out = new(NnfDataMovementCommandStatus)
		(*in).DeepCopyInto(*out)
	}
	in.ResourceError.DeepCopyInto(&out.ResourceError)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfDataMovementStatus.
func (in *NnfDataMovementStatus) DeepCopy() *NnfDataMovementStatus {
	if in == nil {
		return nil
	}
	out := new(NnfDataMovementStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfDriveStatus) DeepCopyInto(out *NnfDriveStatus) {
	*out = *in
	out.NnfResourceStatus = in.NnfResourceStatus
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfDriveStatus.
func (in *NnfDriveStatus) DeepCopy() *NnfDriveStatus {
	if in == nil {
		return nil
	}
	out := new(NnfDriveStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfLustreMGT) DeepCopyInto(out *NnfLustreMGT) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfLustreMGT.
func (in *NnfLustreMGT) DeepCopy() *NnfLustreMGT {
	if in == nil {
		return nil
	}
	out := new(NnfLustreMGT)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NnfLustreMGT) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfLustreMGTList) DeepCopyInto(out *NnfLustreMGTList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NnfLustreMGT, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfLustreMGTList.
func (in *NnfLustreMGTList) DeepCopy() *NnfLustreMGTList {
	if in == nil {
		return nil
	}
	out := new(NnfLustreMGTList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NnfLustreMGTList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfLustreMGTSpec) DeepCopyInto(out *NnfLustreMGTSpec) {
	*out = *in
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.FsNameBlackList != nil {
		in, out := &in.FsNameBlackList, &out.FsNameBlackList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.FsNameStartReference = in.FsNameStartReference
	if in.ClaimList != nil {
		in, out := &in.ClaimList, &out.ClaimList
		*out = make([]v1.ObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.CommandList != nil {
		in, out := &in.CommandList, &out.CommandList
		*out = make([]NnfLustreMGTSpecCommand, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfLustreMGTSpec.
func (in *NnfLustreMGTSpec) DeepCopy() *NnfLustreMGTSpec {
	if in == nil {
		return nil
	}
	out := new(NnfLustreMGTSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfLustreMGTSpecCommand) DeepCopyInto(out *NnfLustreMGTSpecCommand) {
	*out = *in
	out.Reference = in.Reference
	if in.Commands != nil {
		in, out := &in.Commands, &out.Commands
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfLustreMGTSpecCommand.
func (in *NnfLustreMGTSpecCommand) DeepCopy() *NnfLustreMGTSpecCommand {
	if in == nil {
		return nil
	}
	out := new(NnfLustreMGTSpecCommand)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfLustreMGTStatus) DeepCopyInto(out *NnfLustreMGTStatus) {
	*out = *in
	if in.ClaimList != nil {
		in, out := &in.ClaimList, &out.ClaimList
		*out = make([]NnfLustreMGTStatusClaim, len(*in))
		copy(*out, *in)
	}
	if in.CommandList != nil {
		in, out := &in.CommandList, &out.CommandList
		*out = make([]NnfLustreMGTStatusCommand, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.ResourceError.DeepCopyInto(&out.ResourceError)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfLustreMGTStatus.
func (in *NnfLustreMGTStatus) DeepCopy() *NnfLustreMGTStatus {
	if in == nil {
		return nil
	}
	out := new(NnfLustreMGTStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfLustreMGTStatusClaim) DeepCopyInto(out *NnfLustreMGTStatusClaim) {
	*out = *in
	out.Reference = in.Reference
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfLustreMGTStatusClaim.
func (in *NnfLustreMGTStatusClaim) DeepCopy() *NnfLustreMGTStatusClaim {
	if in == nil {
		return nil
	}
	out := new(NnfLustreMGTStatusClaim)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfLustreMGTStatusCommand) DeepCopyInto(out *NnfLustreMGTStatusCommand) {
	*out = *in
	out.Reference = in.Reference
	in.ResourceError.DeepCopyInto(&out.ResourceError)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfLustreMGTStatusCommand.
func (in *NnfLustreMGTStatusCommand) DeepCopy() *NnfLustreMGTStatusCommand {
	if in == nil {
		return nil
	}
	out := new(NnfLustreMGTStatusCommand)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfMPISpec) DeepCopyInto(out *NnfMPISpec) {
	*out = *in
	in.Launcher.DeepCopyInto(&out.Launcher)
	in.Worker.DeepCopyInto(&out.Worker)
	if in.SlotsPerWorker != nil {
		in, out := &in.SlotsPerWorker, &out.SlotsPerWorker
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfMPISpec.
func (in *NnfMPISpec) DeepCopy() *NnfMPISpec {
	if in == nil {
		return nil
	}
	out := new(NnfMPISpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfNode) DeepCopyInto(out *NnfNode) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfNode.
func (in *NnfNode) DeepCopy() *NnfNode {
	if in == nil {
		return nil
	}
	out := new(NnfNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NnfNode) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfNodeBlockStorage) DeepCopyInto(out *NnfNodeBlockStorage) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfNodeBlockStorage.
func (in *NnfNodeBlockStorage) DeepCopy() *NnfNodeBlockStorage {
	if in == nil {
		return nil
	}
	out := new(NnfNodeBlockStorage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NnfNodeBlockStorage) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfNodeBlockStorageAccessStatus) DeepCopyInto(out *NnfNodeBlockStorageAccessStatus) {
	*out = *in
	if in.DevicePaths != nil {
		in, out := &in.DevicePaths, &out.DevicePaths
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfNodeBlockStorageAccessStatus.
func (in *NnfNodeBlockStorageAccessStatus) DeepCopy() *NnfNodeBlockStorageAccessStatus {
	if in == nil {
		return nil
	}
	out := new(NnfNodeBlockStorageAccessStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfNodeBlockStorageAllocationSpec) DeepCopyInto(out *NnfNodeBlockStorageAllocationSpec) {
	*out = *in
	if in.Access != nil {
		in, out := &in.Access, &out.Access
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfNodeBlockStorageAllocationSpec.
func (in *NnfNodeBlockStorageAllocationSpec) DeepCopy() *NnfNodeBlockStorageAllocationSpec {
	if in == nil {
		return nil
	}
	out := new(NnfNodeBlockStorageAllocationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfNodeBlockStorageAllocationStatus) DeepCopyInto(out *NnfNodeBlockStorageAllocationStatus) {
	*out = *in
	if in.Accesses != nil {
		in, out := &in.Accesses, &out.Accesses
		*out = make(map[string]NnfNodeBlockStorageAccessStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Devices != nil {
		in, out := &in.Devices, &out.Devices
		*out = make([]NnfNodeBlockStorageDeviceStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfNodeBlockStorageAllocationStatus.
func (in *NnfNodeBlockStorageAllocationStatus) DeepCopy() *NnfNodeBlockStorageAllocationStatus {
	if in == nil {
		return nil
	}
	out := new(NnfNodeBlockStorageAllocationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfNodeBlockStorageDeviceStatus) DeepCopyInto(out *NnfNodeBlockStorageDeviceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfNodeBlockStorageDeviceStatus.
func (in *NnfNodeBlockStorageDeviceStatus) DeepCopy() *NnfNodeBlockStorageDeviceStatus {
	if in == nil {
		return nil
	}
	out := new(NnfNodeBlockStorageDeviceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfNodeBlockStorageList) DeepCopyInto(out *NnfNodeBlockStorageList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NnfNodeBlockStorage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfNodeBlockStorageList.
func (in *NnfNodeBlockStorageList) DeepCopy() *NnfNodeBlockStorageList {
	if in == nil {
		return nil
	}
	out := new(NnfNodeBlockStorageList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NnfNodeBlockStorageList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfNodeBlockStorageSpec) DeepCopyInto(out *NnfNodeBlockStorageSpec) {
	*out = *in
	if in.Allocations != nil {
		in, out := &in.Allocations, &out.Allocations
		*out = make([]NnfNodeBlockStorageAllocationSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfNodeBlockStorageSpec.
func (in *NnfNodeBlockStorageSpec) DeepCopy() *NnfNodeBlockStorageSpec {
	if in == nil {
		return nil
	}
	out := new(NnfNodeBlockStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfNodeBlockStorageStatus) DeepCopyInto(out *NnfNodeBlockStorageStatus) {
	*out = *in
	if in.Allocations != nil {
		in, out := &in.Allocations, &out.Allocations
		*out = make([]NnfNodeBlockStorageAllocationStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.ResourceError.DeepCopyInto(&out.ResourceError)
	in.PodStartTime.DeepCopyInto(&out.PodStartTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfNodeBlockStorageStatus.
func (in *NnfNodeBlockStorageStatus) DeepCopy() *NnfNodeBlockStorageStatus {
	if in == nil {
		return nil
	}
	out := new(NnfNodeBlockStorageStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfNodeECData) DeepCopyInto(out *NnfNodeECData) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfNodeECData.
func (in *NnfNodeECData) DeepCopy() *NnfNodeECData {
	if in == nil {
		return nil
	}
	out := new(NnfNodeECData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NnfNodeECData) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfNodeECDataList) DeepCopyInto(out *NnfNodeECDataList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NnfNodeECData, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfNodeECDataList.
func (in *NnfNodeECDataList) DeepCopy() *NnfNodeECDataList {
	if in == nil {
		return nil
	}
	out := new(NnfNodeECDataList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NnfNodeECDataList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfNodeECDataSpec) DeepCopyInto(out *NnfNodeECDataSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfNodeECDataSpec.
func (in *NnfNodeECDataSpec) DeepCopy() *NnfNodeECDataSpec {
	if in == nil {
		return nil
	}
	out := new(NnfNodeECDataSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfNodeECDataStatus) DeepCopyInto(out *NnfNodeECDataStatus) {
	*out = *in
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = make(map[string]NnfNodeECPrivateData, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(NnfNodeECPrivateData, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfNodeECDataStatus.
func (in *NnfNodeECDataStatus) DeepCopy() *NnfNodeECDataStatus {
	if in == nil {
		return nil
	}
	out := new(NnfNodeECDataStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in NnfNodeECPrivateData) DeepCopyInto(out *NnfNodeECPrivateData) {
	{
		in := &in
		*out = make(NnfNodeECPrivateData, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfNodeECPrivateData.
func (in NnfNodeECPrivateData) DeepCopy() NnfNodeECPrivateData {
	if in == nil {
		return nil
	}
	out := new(NnfNodeECPrivateData)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfNodeList) DeepCopyInto(out *NnfNodeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NnfNode, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfNodeList.
func (in *NnfNodeList) DeepCopy() *NnfNodeList {
	if in == nil {
		return nil
	}
	out := new(NnfNodeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NnfNodeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfNodeSpec) DeepCopyInto(out *NnfNodeSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfNodeSpec.
func (in *NnfNodeSpec) DeepCopy() *NnfNodeSpec {
	if in == nil {
		return nil
	}
	out := new(NnfNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfNodeStatus) DeepCopyInto(out *NnfNodeStatus) {
	*out = *in
	if in.Servers != nil {
		in, out := &in.Servers, &out.Servers
		*out = make([]NnfServerStatus, len(*in))
		copy(*out, *in)
	}
	if in.Drives != nil {
		in, out := &in.Drives, &out.Drives
		*out = make([]NnfDriveStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfNodeStatus.
func (in *NnfNodeStatus) DeepCopy() *NnfNodeStatus {
	if in == nil {
		return nil
	}
	out := new(NnfNodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfNodeStorage) DeepCopyInto(out *NnfNodeStorage) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfNodeStorage.
func (in *NnfNodeStorage) DeepCopy() *NnfNodeStorage {
	if in == nil {
		return nil
	}
	out := new(NnfNodeStorage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NnfNodeStorage) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfNodeStorageAllocationStatus) DeepCopyInto(out *NnfNodeStorageAllocationStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfNodeStorageAllocationStatus.
func (in *NnfNodeStorageAllocationStatus) DeepCopy() *NnfNodeStorageAllocationStatus {
	if in == nil {
		return nil
	}
	out := new(NnfNodeStorageAllocationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfNodeStorageList) DeepCopyInto(out *NnfNodeStorageList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NnfNodeStorage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfNodeStorageList.
func (in *NnfNodeStorageList) DeepCopy() *NnfNodeStorageList {
	if in == nil {
		return nil
	}
	out := new(NnfNodeStorageList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NnfNodeStorageList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfNodeStorageSpec) DeepCopyInto(out *NnfNodeStorageSpec) {
	*out = *in
	if in.CommandVariables != nil {
		in, out := &in.CommandVariables, &out.CommandVariables
		*out = make([]CommandVariablesSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.LustreStorage.DeepCopyInto(&out.LustreStorage)
	out.BlockReference = in.BlockReference
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfNodeStorageSpec.
func (in *NnfNodeStorageSpec) DeepCopy() *NnfNodeStorageSpec {
	if in == nil {
		return nil
	}
	out := new(NnfNodeStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfNodeStorageStatus) DeepCopyInto(out *NnfNodeStorageStatus) {
	*out = *in
	if in.Allocations != nil {
		in, out := &in.Allocations, &out.Allocations
		*out = make([]NnfNodeStorageAllocationStatus, len(*in))
		copy(*out, *in)
	}
	in.ResourceError.DeepCopyInto(&out.ResourceError)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfNodeStorageStatus.
func (in *NnfNodeStorageStatus) DeepCopy() *NnfNodeStorageStatus {
	if in == nil {
		return nil
	}
	out := new(NnfNodeStorageStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfPodSpec) DeepCopyInto(out *NnfPodSpec) {
	*out = *in
	if in.Containers != nil {
		in, out := &in.Containers, &out.Containers
		*out = make([]NnfContainer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.InitContainers != nil {
		in, out := &in.InitContainers, &out.InitContainers
		*out = make([]NnfContainer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]v1.Volume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TerminationGracePeriodSeconds != nil {
		in, out := &in.TerminationGracePeriodSeconds, &out.TerminationGracePeriodSeconds
		*out = new(int64)
		**out = **in
	}
	if in.ShareProcessNamespace != nil {
		in, out := &in.ShareProcessNamespace, &out.ShareProcessNamespace
		*out = new(bool)
		**out = **in
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.AutomountServiceAccountToken != nil {
		in, out := &in.AutomountServiceAccountToken, &out.AutomountServiceAccountToken
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfPodSpec.
func (in *NnfPodSpec) DeepCopy() *NnfPodSpec {
	if in == nil {
		return nil
	}
	out := new(NnfPodSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfPortManager) DeepCopyInto(out *NnfPortManager) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfPortManager.
func (in *NnfPortManager) DeepCopy() *NnfPortManager {
	if in == nil {
		return nil
	}
	out := new(NnfPortManager)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NnfPortManager) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfPortManagerAllocationSpec) DeepCopyInto(out *NnfPortManagerAllocationSpec) {
	*out = *in
	out.Requester = in.Requester
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfPortManagerAllocationSpec.
func (in *NnfPortManagerAllocationSpec) DeepCopy() *NnfPortManagerAllocationSpec {
	if in == nil {
		return nil
	}
	out := new(NnfPortManagerAllocationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfPortManagerAllocationStatus) DeepCopyInto(out *NnfPortManagerAllocationStatus) {
	*out = *in
	if in.Requester != nil {
		in, out := &in.Requester, &out.Requester
		*out = new(v1.ObjectReference)
		**out = **in
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]uint16, len(*in))
		copy(*out, *in)
	}
	if in.TimeUnallocated != nil {
		in, out := &in.TimeUnallocated, &out.TimeUnallocated
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfPortManagerAllocationStatus.
func (in *NnfPortManagerAllocationStatus) DeepCopy() *NnfPortManagerAllocationStatus {
	if in == nil {
		return nil
	}
	out := new(NnfPortManagerAllocationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfPortManagerList) DeepCopyInto(out *NnfPortManagerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NnfPortManager, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfPortManagerList.
func (in *NnfPortManagerList) DeepCopy() *NnfPortManagerList {
	if in == nil {
		return nil
	}
	out := new(NnfPortManagerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NnfPortManagerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfPortManagerSpec) DeepCopyInto(out *NnfPortManagerSpec) {
	*out = *in
	out.SystemConfiguration = in.SystemConfiguration
	if in.Allocations != nil {
		in, out := &in.Allocations, &out.Allocations
		*out = make([]NnfPortManagerAllocationSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfPortManagerSpec.
func (in *NnfPortManagerSpec) DeepCopy() *NnfPortManagerSpec {
	if in == nil {
		return nil
	}
	out := new(NnfPortManagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfPortManagerStatus) DeepCopyInto(out *NnfPortManagerStatus) {
	*out = *in
	if in.Allocations != nil {
		in, out := &in.Allocations, &out.Allocations
		*out = make([]NnfPortManagerAllocationStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfPortManagerStatus.
func (in *NnfPortManagerStatus) DeepCopy() *NnfPortManagerStatus {
	if in == nil {
		return nil
	}
	out := new(NnfPortManagerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfResourceStatus) DeepCopyInto(out *NnfResourceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfResourceStatus.
func (in *NnfResourceStatus) DeepCopy() *NnfResourceStatus {
	if in == nil {
		return nil
	}
	out := new(NnfResourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfServerStatus) DeepCopyInto(out *NnfServerStatus) {
	*out = *in
	out.NnfResourceStatus = in.NnfResourceStatus
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfServerStatus.
func (in *NnfServerStatus) DeepCopy() *NnfServerStatus {
	if in == nil {
		return nil
	}
	out := new(NnfServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfStorage) DeepCopyInto(out *NnfStorage) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfStorage.
func (in *NnfStorage) DeepCopy() *NnfStorage {
	if in == nil {
		return nil
	}
	out := new(NnfStorage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NnfStorage) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfStorageAllocationNodes) DeepCopyInto(out *NnfStorageAllocationNodes) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfStorageAllocationNodes.
func (in *NnfStorageAllocationNodes) DeepCopy() *NnfStorageAllocationNodes {
	if in == nil {
		return nil
	}
	out := new(NnfStorageAllocationNodes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfStorageAllocationSetSpec) DeepCopyInto(out *NnfStorageAllocationSetSpec) {
	*out = *in
	out.NnfStorageLustreSpec = in.NnfStorageLustreSpec
	if in.CommandVariables != nil {
		in, out := &in.CommandVariables, &out.CommandVariables
		*out = make([]CommandVariablesSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]NnfStorageAllocationNodes, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfStorageAllocationSetSpec.
func (in *NnfStorageAllocationSetSpec) DeepCopy() *NnfStorageAllocationSetSpec {
	if in == nil {
		return nil
	}
	out := new(NnfStorageAllocationSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfStorageAllocationSetStatus) DeepCopyInto(out *NnfStorageAllocationSetStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfStorageAllocationSetStatus.
func (in *NnfStorageAllocationSetStatus) DeepCopy() *NnfStorageAllocationSetStatus {
	if in == nil {
		return nil
	}
	out := new(NnfStorageAllocationSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfStorageList) DeepCopyInto(out *NnfStorageList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NnfStorage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfStorageList.
func (in *NnfStorageList) DeepCopy() *NnfStorageList {
	if in == nil {
		return nil
	}
	out := new(NnfStorageList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NnfStorageList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfStorageLustreComponents) DeepCopyInto(out *NnfStorageLustreComponents) {
	*out = *in
	if in.MDTs != nil {
		in, out := &in.MDTs, &out.MDTs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MGTs != nil {
		in, out := &in.MGTs, &out.MGTs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MGTMDTs != nil {
		in, out := &in.MGTMDTs, &out.MGTMDTs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.OSTs != nil {
		in, out := &in.OSTs, &out.OSTs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NNFNodes != nil {
		in, out := &in.NNFNodes, &out.NNFNodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfStorageLustreComponents.
func (in *NnfStorageLustreComponents) DeepCopy() *NnfStorageLustreComponents {
	if in == nil {
		return nil
	}
	out := new(NnfStorageLustreComponents)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfStorageLustreSpec) DeepCopyInto(out *NnfStorageLustreSpec) {
	*out = *in
	out.PersistentMgsReference = in.PersistentMgsReference
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfStorageLustreSpec.
func (in *NnfStorageLustreSpec) DeepCopy() *NnfStorageLustreSpec {
	if in == nil {
		return nil
	}
	out := new(NnfStorageLustreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfStorageLustreStatus) DeepCopyInto(out *NnfStorageLustreStatus) {
	*out = *in
	out.LustreMgtReference = in.LustreMgtReference
	in.LustreComponents.DeepCopyInto(&out.LustreComponents)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfStorageLustreStatus.
func (in *NnfStorageLustreStatus) DeepCopy() *NnfStorageLustreStatus {
	if in == nil {
		return nil
	}
	out := new(NnfStorageLustreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfStorageProfile) DeepCopyInto(out *NnfStorageProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Data.DeepCopyInto(&out.Data)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfStorageProfile.
func (in *NnfStorageProfile) DeepCopy() *NnfStorageProfile {
	if in == nil {
		return nil
	}
	out := new(NnfStorageProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NnfStorageProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfStorageProfileBlockDevice) DeepCopyInto(out *NnfStorageProfileBlockDevice) {
	*out = *in
	in.RabbitCommands.DeepCopyInto(&out.RabbitCommands)
	in.ComputeCommands.DeepCopyInto(&out.ComputeCommands)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfStorageProfileBlockDevice.
func (in *NnfStorageProfileBlockDevice) DeepCopy() *NnfStorageProfileBlockDevice {
	if in == nil {
		return nil
	}
	out := new(NnfStorageProfileBlockDevice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfStorageProfileBlockDeviceUserCommands) DeepCopyInto(out *NnfStorageProfileBlockDeviceUserCommands) {
	*out = *in
	if in.PreActivate != nil {
		in, out := &in.PreActivate, &out.PreActivate
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PostActivate != nil {
		in, out := &in.PostActivate, &out.PostActivate
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PreDeactivate != nil {
		in, out := &in.PreDeactivate, &out.PreDeactivate
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PostDeactivate != nil {
		in, out := &in.PostDeactivate, &out.PostDeactivate
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfStorageProfileBlockDeviceUserCommands.
func (in *NnfStorageProfileBlockDeviceUserCommands) DeepCopy() *NnfStorageProfileBlockDeviceUserCommands {
	if in == nil {
		return nil
	}
	out := new(NnfStorageProfileBlockDeviceUserCommands)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfStorageProfileComputeBlockDeviceCommands) DeepCopyInto(out *NnfStorageProfileComputeBlockDeviceCommands) {
	*out = *in
	out.VgChange = in.VgChange
	out.LvChange = in.LvChange
	in.UserCommands.DeepCopyInto(&out.UserCommands)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfStorageProfileComputeBlockDeviceCommands.
func (in *NnfStorageProfileComputeBlockDeviceCommands) DeepCopy() *NnfStorageProfileComputeBlockDeviceCommands {
	if in == nil {
		return nil
	}
	out := new(NnfStorageProfileComputeBlockDeviceCommands)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfStorageProfileComputeFileSystemCommands) DeepCopyInto(out *NnfStorageProfileComputeFileSystemCommands) {
	*out = *in
	in.UserCommands.DeepCopyInto(&out.UserCommands)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfStorageProfileComputeFileSystemCommands.
func (in *NnfStorageProfileComputeFileSystemCommands) DeepCopy() *NnfStorageProfileComputeFileSystemCommands {
	if in == nil {
		return nil
	}
	out := new(NnfStorageProfileComputeFileSystemCommands)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfStorageProfileData) DeepCopyInto(out *NnfStorageProfileData) {
	*out = *in
	in.LustreStorage.DeepCopyInto(&out.LustreStorage)
	in.GFS2Storage.DeepCopyInto(&out.GFS2Storage)
	in.XFSStorage.DeepCopyInto(&out.XFSStorage)
	in.RawStorage.DeepCopyInto(&out.RawStorage)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfStorageProfileData.
func (in *NnfStorageProfileData) DeepCopy() *NnfStorageProfileData {
	if in == nil {
		return nil
	}
	out := new(NnfStorageProfileData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfStorageProfileFileSystem) DeepCopyInto(out *NnfStorageProfileFileSystem) {
	*out = *in
	in.RabbitCommands.DeepCopyInto(&out.RabbitCommands)
	in.ComputeCommands.DeepCopyInto(&out.ComputeCommands)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfStorageProfileFileSystem.
func (in *NnfStorageProfileFileSystem) DeepCopy() *NnfStorageProfileFileSystem {
	if in == nil {
		return nil
	}
	out := new(NnfStorageProfileFileSystem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfStorageProfileFileSystemUserCommands) DeepCopyInto(out *NnfStorageProfileFileSystemUserCommands) {
	*out = *in
	if in.PreMount != nil {
		in, out := &in.PreMount, &out.PreMount
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PostMount != nil {
		in, out := &in.PostMount, &out.PostMount
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PreUnmount != nil {
		in, out := &in.PreUnmount, &out.PreUnmount
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PostUnmount != nil {
		in, out := &in.PostUnmount, &out.PostUnmount
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfStorageProfileFileSystemUserCommands.
func (in *NnfStorageProfileFileSystemUserCommands) DeepCopy() *NnfStorageProfileFileSystemUserCommands {
	if in == nil {
		return nil
	}
	out := new(NnfStorageProfileFileSystemUserCommands)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfStorageProfileGFS2Data) DeepCopyInto(out *NnfStorageProfileGFS2Data) {
	*out = *in
	in.NnfStorageProfileSharedData.DeepCopyInto(&out.NnfStorageProfileSharedData)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfStorageProfileGFS2Data.
func (in *NnfStorageProfileGFS2Data) DeepCopy() *NnfStorageProfileGFS2Data {
	if in == nil {
		return nil
	}
	out := new(NnfStorageProfileGFS2Data)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfStorageProfileLVMLvChangeCmdLines) DeepCopyInto(out *NnfStorageProfileLVMLvChangeCmdLines) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfStorageProfileLVMLvChangeCmdLines.
func (in *NnfStorageProfileLVMLvChangeCmdLines) DeepCopy() *NnfStorageProfileLVMLvChangeCmdLines {
	if in == nil {
		return nil
	}
	out := new(NnfStorageProfileLVMLvChangeCmdLines)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfStorageProfileLVMRebuildCmdLines) DeepCopyInto(out *NnfStorageProfileLVMRebuildCmdLines) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfStorageProfileLVMRebuildCmdLines.
func (in *NnfStorageProfileLVMRebuildCmdLines) DeepCopy() *NnfStorageProfileLVMRebuildCmdLines {
	if in == nil {
		return nil
	}
	out := new(NnfStorageProfileLVMRebuildCmdLines)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfStorageProfileLVMVgChangeCmdLines) DeepCopyInto(out *NnfStorageProfileLVMVgChangeCmdLines) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfStorageProfileLVMVgChangeCmdLines.
func (in *NnfStorageProfileLVMVgChangeCmdLines) DeepCopy() *NnfStorageProfileLVMVgChangeCmdLines {
	if in == nil {
		return nil
	}
	out := new(NnfStorageProfileLVMVgChangeCmdLines)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfStorageProfileList) DeepCopyInto(out *NnfStorageProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NnfStorageProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfStorageProfileList.
func (in *NnfStorageProfileList) DeepCopy() *NnfStorageProfileList {
	if in == nil {
		return nil
	}
	out := new(NnfStorageProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NnfStorageProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfStorageProfileLustreClientCmdLines) DeepCopyInto(out *NnfStorageProfileLustreClientCmdLines) {
	*out = *in
	if in.RabbitPostSetup != nil {
		in, out := &in.RabbitPostSetup, &out.RabbitPostSetup
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RabbitPreTeardown != nil {
		in, out := &in.RabbitPreTeardown, &out.RabbitPreTeardown
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RabbitPreMount != nil {
		in, out := &in.RabbitPreMount, &out.RabbitPreMount
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RabbitPostMount != nil {
		in, out := &in.RabbitPostMount, &out.RabbitPostMount
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RabbitPreUnmount != nil {
		in, out := &in.RabbitPreUnmount, &out.RabbitPreUnmount
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RabbitPostUnmount != nil {
		in, out := &in.RabbitPostUnmount, &out.RabbitPostUnmount
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ComputePreMount != nil {
		in, out := &in.ComputePreMount, &out.ComputePreMount
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ComputePostMount != nil {
		in, out := &in.ComputePostMount, &out.ComputePostMount
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ComputePreUnmount != nil {
		in, out := &in.ComputePreUnmount, &out.ComputePreUnmount
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ComputePostUnmount != nil {
		in, out := &in.ComputePostUnmount, &out.ComputePostUnmount
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfStorageProfileLustreClientCmdLines.
func (in *NnfStorageProfileLustreClientCmdLines) DeepCopy() *NnfStorageProfileLustreClientCmdLines {
	if in == nil {
		return nil
	}
	out := new(NnfStorageProfileLustreClientCmdLines)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfStorageProfileLustreClientOptions) DeepCopyInto(out *NnfStorageProfileLustreClientOptions) {
	*out = *in
	in.CmdLines.DeepCopyInto(&out.CmdLines)
	if in.VariableOverride != nil {
		in, out := &in.VariableOverride, &out.VariableOverride
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfStorageProfileLustreClientOptions.
func (in *NnfStorageProfileLustreClientOptions) DeepCopy() *NnfStorageProfileLustreClientOptions {
	if in == nil {
		return nil
	}
	out := new(NnfStorageProfileLustreClientOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfStorageProfileLustreCmdLines) DeepCopyInto(out *NnfStorageProfileLustreCmdLines) {
	*out = *in
	if in.PostActivate != nil {
		in, out := &in.PostActivate, &out.PostActivate
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PreDeactivate != nil {
		in, out := &in.PreDeactivate, &out.PreDeactivate
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfStorageProfileLustreCmdLines.
func (in *NnfStorageProfileLustreCmdLines) DeepCopy() *NnfStorageProfileLustreCmdLines {
	if in == nil {
		return nil
	}
	out := new(NnfStorageProfileLustreCmdLines)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfStorageProfileLustreData) DeepCopyInto(out *NnfStorageProfileLustreData) {
	*out = *in
	in.MgtOptions.DeepCopyInto(&out.MgtOptions)
	in.MdtOptions.DeepCopyInto(&out.MdtOptions)
	in.MgtMdtOptions.DeepCopyInto(&out.MgtMdtOptions)
	in.OstOptions.DeepCopyInto(&out.OstOptions)
	in.ClientOptions.DeepCopyInto(&out.ClientOptions)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfStorageProfileLustreData.
func (in *NnfStorageProfileLustreData) DeepCopy() *NnfStorageProfileLustreData {
	if in == nil {
		return nil
	}
	out := new(NnfStorageProfileLustreData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfStorageProfileLustreMdtOptions) DeepCopyInto(out *NnfStorageProfileLustreMdtOptions) {
	*out = *in
	in.NnfStorageProfileLustreTargetOptions.DeepCopyInto(&out.NnfStorageProfileLustreTargetOptions)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfStorageProfileLustreMdtOptions.
func (in *NnfStorageProfileLustreMdtOptions) DeepCopy() *NnfStorageProfileLustreMdtOptions {
	if in == nil {
		return nil
	}
	out := new(NnfStorageProfileLustreMdtOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfStorageProfileLustreMgtMdtOptions) DeepCopyInto(out *NnfStorageProfileLustreMgtMdtOptions) {
	*out = *in
	in.NnfStorageProfileLustreTargetOptions.DeepCopyInto(&out.NnfStorageProfileLustreTargetOptions)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfStorageProfileLustreMgtMdtOptions.
func (in *NnfStorageProfileLustreMgtMdtOptions) DeepCopy() *NnfStorageProfileLustreMgtMdtOptions {
	if in == nil {
		return nil
	}
	out := new(NnfStorageProfileLustreMgtMdtOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfStorageProfileLustreMgtOptions) DeepCopyInto(out *NnfStorageProfileLustreMgtOptions) {
	*out = *in
	in.NnfStorageProfileLustreTargetOptions.DeepCopyInto(&out.NnfStorageProfileLustreTargetOptions)
	if in.PreMountCommands != nil {
		in, out := &in.PreMountCommands, &out.PreMountCommands
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfStorageProfileLustreMgtOptions.
func (in *NnfStorageProfileLustreMgtOptions) DeepCopy() *NnfStorageProfileLustreMgtOptions {
	if in == nil {
		return nil
	}
	out := new(NnfStorageProfileLustreMgtOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfStorageProfileLustreOstOptions) DeepCopyInto(out *NnfStorageProfileLustreOstOptions) {
	*out = *in
	in.NnfStorageProfileLustreTargetOptions.DeepCopyInto(&out.NnfStorageProfileLustreTargetOptions)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfStorageProfileLustreOstOptions.
func (in *NnfStorageProfileLustreOstOptions) DeepCopy() *NnfStorageProfileLustreOstOptions {
	if in == nil {
		return nil
	}
	out := new(NnfStorageProfileLustreOstOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfStorageProfileLustreTargetOptions) DeepCopyInto(out *NnfStorageProfileLustreTargetOptions) {
	*out = *in
	in.CmdLines.DeepCopyInto(&out.CmdLines)
	if in.VariableOverride != nil {
		in, out := &in.VariableOverride, &out.VariableOverride
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.StorageLabels != nil {
		in, out := &in.StorageLabels, &out.StorageLabels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfStorageProfileLustreTargetOptions.
func (in *NnfStorageProfileLustreTargetOptions) DeepCopy() *NnfStorageProfileLustreTargetOptions {
	if in == nil {
		return nil
	}
	out := new(NnfStorageProfileLustreTargetOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfStorageProfileRabbitBlockDeviceCommands) DeepCopyInto(out *NnfStorageProfileRabbitBlockDeviceCommands) {
	*out = *in
	out.VgChange = in.VgChange
	out.LVMRebuild = in.LVMRebuild
	out.LvChange = in.LvChange
	in.UserCommands.DeepCopyInto(&out.UserCommands)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfStorageProfileRabbitBlockDeviceCommands.
func (in *NnfStorageProfileRabbitBlockDeviceCommands) DeepCopy() *NnfStorageProfileRabbitBlockDeviceCommands {
	if in == nil {
		return nil
	}
	out := new(NnfStorageProfileRabbitBlockDeviceCommands)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfStorageProfileRabbitFileSystemCommands) DeepCopyInto(out *NnfStorageProfileRabbitFileSystemCommands) {
	*out = *in
	in.UserCommands.DeepCopyInto(&out.UserCommands)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfStorageProfileRabbitFileSystemCommands.
func (in *NnfStorageProfileRabbitFileSystemCommands) DeepCopy() *NnfStorageProfileRabbitFileSystemCommands {
	if in == nil {
		return nil
	}
	out := new(NnfStorageProfileRabbitFileSystemCommands)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfStorageProfileRawData) DeepCopyInto(out *NnfStorageProfileRawData) {
	*out = *in
	in.NnfStorageProfileSharedData.DeepCopyInto(&out.NnfStorageProfileSharedData)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfStorageProfileRawData.
func (in *NnfStorageProfileRawData) DeepCopy() *NnfStorageProfileRawData {
	if in == nil {
		return nil
	}
	out := new(NnfStorageProfileRawData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfStorageProfileSharedData) DeepCopyInto(out *NnfStorageProfileSharedData) {
	*out = *in
	in.FileSystemCommands.DeepCopyInto(&out.FileSystemCommands)
	in.BlockDeviceCommands.DeepCopyInto(&out.BlockDeviceCommands)
	in.UserCommands.DeepCopyInto(&out.UserCommands)
	if in.StorageLabels != nil {
		in, out := &in.StorageLabels, &out.StorageLabels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.VariableOverride != nil {
		in, out := &in.VariableOverride, &out.VariableOverride
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfStorageProfileSharedData.
func (in *NnfStorageProfileSharedData) DeepCopy() *NnfStorageProfileSharedData {
	if in == nil {
		return nil
	}
	out := new(NnfStorageProfileSharedData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfStorageProfileUserCommands) DeepCopyInto(out *NnfStorageProfileUserCommands) {
	*out = *in
	if in.PostActivate != nil {
		in, out := &in.PostActivate, &out.PostActivate
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PreDeactivate != nil {
		in, out := &in.PreDeactivate, &out.PreDeactivate
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PostSetup != nil {
		in, out := &in.PostSetup, &out.PostSetup
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PreTeardown != nil {
		in, out := &in.PreTeardown, &out.PreTeardown
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfStorageProfileUserCommands.
func (in *NnfStorageProfileUserCommands) DeepCopy() *NnfStorageProfileUserCommands {
	if in == nil {
		return nil
	}
	out := new(NnfStorageProfileUserCommands)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfStorageProfileXFSData) DeepCopyInto(out *NnfStorageProfileXFSData) {
	*out = *in
	in.NnfStorageProfileSharedData.DeepCopyInto(&out.NnfStorageProfileSharedData)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfStorageProfileXFSData.
func (in *NnfStorageProfileXFSData) DeepCopy() *NnfStorageProfileXFSData {
	if in == nil {
		return nil
	}
	out := new(NnfStorageProfileXFSData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfStorageSpec) DeepCopyInto(out *NnfStorageSpec) {
	*out = *in
	if in.AllocationSets != nil {
		in, out := &in.AllocationSets, &out.AllocationSets
		*out = make([]NnfStorageAllocationSetSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfStorageSpec.
func (in *NnfStorageSpec) DeepCopy() *NnfStorageSpec {
	if in == nil {
		return nil
	}
	out := new(NnfStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfStorageStatus) DeepCopyInto(out *NnfStorageStatus) {
	*out = *in
	in.NnfStorageLustreStatus.DeepCopyInto(&out.NnfStorageLustreStatus)
	if in.AllocationSets != nil {
		in, out := &in.AllocationSets, &out.AllocationSets
		*out = make([]NnfStorageAllocationSetStatus, len(*in))
		copy(*out, *in)
	}
	in.ResourceError.DeepCopyInto(&out.ResourceError)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfStorageStatus.
func (in *NnfStorageStatus) DeepCopy() *NnfStorageStatus {
	if in == nil {
		return nil
	}
	out := new(NnfStorageStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfSystemStorage) DeepCopyInto(out *NnfSystemStorage) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfSystemStorage.
func (in *NnfSystemStorage) DeepCopy() *NnfSystemStorage {
	if in == nil {
		return nil
	}
	out := new(NnfSystemStorage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NnfSystemStorage) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfSystemStorageList) DeepCopyInto(out *NnfSystemStorageList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NnfSystemStorage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfSystemStorageList.
func (in *NnfSystemStorageList) DeepCopy() *NnfSystemStorageList {
	if in == nil {
		return nil
	}
	out := new(NnfSystemStorageList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NnfSystemStorageList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfSystemStorageSpec) DeepCopyInto(out *NnfSystemStorageSpec) {
	*out = *in
	out.SystemConfiguration = in.SystemConfiguration
	if in.ExcludeRabbits != nil {
		in, out := &in.ExcludeRabbits, &out.ExcludeRabbits
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IncludeRabbits != nil {
		in, out := &in.IncludeRabbits, &out.IncludeRabbits
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExcludeComputes != nil {
		in, out := &in.ExcludeComputes, &out.ExcludeComputes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IncludeComputes != nil {
		in, out := &in.IncludeComputes, &out.IncludeComputes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ComputesPattern != nil {
		in, out := &in.ComputesPattern, &out.ComputesPattern
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	out.StorageProfile = in.StorageProfile
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfSystemStorageSpec.
func (in *NnfSystemStorageSpec) DeepCopy() *NnfSystemStorageSpec {
	if in == nil {
		return nil
	}
	out := new(NnfSystemStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NnfSystemStorageStatus) DeepCopyInto(out *NnfSystemStorageStatus) {
	*out = *in
	in.ResourceError.DeepCopyInto(&out.ResourceError)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NnfSystemStorageStatus.
func (in *NnfSystemStorageStatus) DeepCopy() *NnfSystemStorageStatus {
	if in == nil {
		return nil
	}
	out := new(NnfSystemStorageStatus)
	in.DeepCopyInto(out)
	return out
}
