apiVersion: nnf.cray.hpe.com/v1alpha1
kind: NnfNodeStorage
metadata:
  name: foo-mdt
  namespace: rabbit-02
spec:
  # Add fields here
  capacity: 100000
  fileSystemType: "lustre"
  lustreStorage:
    fileSystemName: "foo"
    targetType: "MDT"
    mgsNode: "rabbit-01@tcp"
    startIndex: 0
    backFs: "zfs"
  count: 1

