apiVersion: nnf.cray.hpe.com/v1alpha1
kind: NnfNodeStorage
metadata:
  name: foo-mgt
  namespace: rabbit-01
spec:
  # Add fields here
  capacity: 100000
  fileSystemName: "foo"
  fileSystemType: "lustre"
  lustreStorage:
    targetType: "MGT"
  servers:
    - id: "0"
      path: "/mnt/foo-mgt"


