apiVersion: nnf.cray.hpe.com/v1alpha1
kind: NnfNodeStorage
metadata:
  name: foo-ost
  namespace: rabbit-03
spec:
  # Add fields here
  capacity: 100000
  fileSystemType: "lustre"
  lustreStorage:
    fileSystemName: "foo"
    targetType: "OST"
    mgsNode: "rabbit-01@tcp"
    startIndex: 0
  count: 1


