apiVersion: nnf.cray.hpe.com/v1alpha1
kind: NnfNodeStorage
metadata:
  name: foo-ost
  namespace: rabbit-03
spec:
  # Add fields here
  capacity: 100000
  fileSystemName: "foo"
  fileSystemType: "lustre"
  lustreStorage:
    targetType: "OST"
    mgsNode: "rabbit-01@tcp"
    index: 0
    backFs: "zfs"
  servers:
    - id: "0"
      path: "/mnt/foo-ost"


