apiVersion: nnf.cray.hpe.com/v1alpha1
kind: NnfNodeStorage
metadata:
  name: foo-mgt
  namespace: rabbit-01
spec:
  # Add fields here
  capacity: 100000
  fileSystemType: "lustre"
  lustreStorage:
    fileSystemName: "foo"
    targetType: "MGT"
  count: 1


