## Append samples you want in your CSV to this file as resources ##
resources:
- nnf_v1alpha10_nnfaccess.yaml
- nnf_v1alpha10_nnfcontainerprofile.yaml
- nnf_v1alpha10_nnfdatamovement.yaml
- nnf_v1alpha10_nnfdatamovementmanager.yaml
- nnf_v1alpha10_nnfdatamovementprofile.yaml
- nnf_v1alpha10_nnflustremgt.yaml
- nnf_v1alpha10_nnfnode.yaml
- nnf_v1alpha10_nnfnodeblockstorage.yaml
- nnf_v1alpha10_nnfnodeecdata.yaml
- nnf_v1alpha10_nnfnodestorage.yaml
- nnf_v1alpha10_nnfportmanager.yaml
- nnf_v1alpha10_nnfstorage.yaml
- nnf_v1alpha10_nnfstorageprofile.yaml
- nnf_v1alpha10_nnfsystemstorage.yaml
- nnf_v1alpha11_nnfaccess.yaml
- nnf_v1alpha11_nnfcontainerprofile.yaml
- nnf_v1alpha11_nnfdatamovement.yaml
- nnf_v1alpha11_nnfdatamovementmanager.yaml
- nnf_v1alpha11_nnfdatamovementprofile.yaml
- nnf_v1alpha11_nnflustremgt.yaml
- nnf_v1alpha11_nnfnode.yaml
- nnf_v1alpha11_nnfnodeblockstorage.yaml
- nnf_v1alpha11_nnfnodeecdata.yaml
- nnf_v1alpha11_nnfcontainerdata.yaml
- nnf_v1alpha11_nnfnodestorage.yaml
- nnf_v1alpha11_nnfportmanager.yaml
- nnf_v1alpha11_nnfstorage.yaml
- nnf_v1alpha11_nnfstorageprofile.yaml
- nnf_v1alpha11_nnfsystemstorage.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
