apiVersion: nnf.cray.hpe.com/v1alpha1
kind: NnfContainerProfile
metadata:
  name: nnfcontainerprofile-sample
  namespace: nnf-system
data:
  backoffLimit: 6
  storages:
    - name: DW_JOB_foo-local-storage
      optional: false
    - name: DW_PERSISTENT_foo-persistent-storage
      optional: false
  template:
    spec:
      # TODO: non-root
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
        - name: foo
          image: alpine:latest
          command:
            - /bin/sh
            - -c
            - |
              echo "starting..."
              sleep 30
              x=$(($RANDOM % 2))
              echo "exiting: $x"
              exit $x
          # TODO get volumes working
          # volumeMounts:
          # - name: foo-local-storage
          #   mountPath: /foo/local
          # - name: foo-persistent-storage
          #   mountPath: /foo/persistent
          # - name: nnf-config
          #   mountPath: /nnf/config
      tolerations:
        - effect: NoSchedule
          key: cray.nnf.node
          operator: Equal
          value: "true"
