apiVersion: nnf.cray.hpe.com/v1alpha1
kind: NnfSystemStorage
metadata:
  labels:
    app.kubernetes.io/name: nnf-sos
    app.kubernetes.io/managed-by: kustomize
  name: nnfsystemstorage-sample
spec:
  type: "raw"
  computesTarget: "all"
  storageProfile:
    name: systemstorage
    namespace: default
    kind: NnfStorageProfile
