apiVersion: nnf.cray.hpe.com/v1alpha1
kind: NnfStorage
metadata:
  name: storage-sample
  namespace: nnf-system
spec:
  uuid: "af7dfc28-2e74-4d60-803c-4a11a72e5b49"
  capacity: 1048576
  nodes:
  - node: kind-worker
    servers:
    - id: "0"
      name: "Rabbit"
