apiVersion: nnf.cray.hpe.com/v1alpha1
kind: NnfDataMovementProfile
metadata:
  labels:
    app.kubernetes.io/name: nnf-sos
    app.kubernetes.io/managed-by: kustomize
  name: nnfdatamovementprofile-sample
data:
  #  Default is true if this instance is the default resource to use
  default: true

  # Slots is the number of slots specified in the MPI hostfile. A value less than 1 disables the use
  # of slots in the hostfile.
  slots: 8

  # MaxSlots is the number of max_slots specified in the MPI hostfile. A value less than 1 disables
  # the use of max_slots in the hostfile.
  maxSlots: 0

  # Command to execute to perform data movement. $VARS are replaced by the nnf software and must
  # be present in the command.
  # Available $VARS:
  #   HOSTFILE: hostfile that is created and used for mpirun. Contains a list of hosts and the
  #             slots/max_slots for each host. This hostfile is created at `/tmp/<dm-name>/hostfile`
  #   UID: User ID that is inherited from the Workflow
  #   GID: Group ID that is inherited from the Workflow
  #   SRC: source for the data movement
  #   DEST destination for the data movement
  command: ulimit -n 2048 && mpirun --allow-run-as-root --hostfile $HOSTFILE dcp --progress 1 --uid $UID --gid $GID $SRC $DEST

  # If true, enable the command's stdout to be saved in the log when the command completes
  # successfully. On failure, the output is always logged.
  logStdout: false

  # Similar to logStdout, store the command's stdout in Status.Message when the command completes
  # successfully. On failure, the output is always stored.
  storeStdout: false

  # NnfDataMovement resources have the ability to collect and store the progress percentage and the
  # last few lines of output in the CommandStatus field. This number is used for the interval to collect
  # the progress data. `dcp --progress N` must be included in the data movement command in order for
  # progress to be collected. A value less than 1 disables this functionality.
  progressIntervalSeconds: 5
