apiVersion: nnf.cray.hpe.com/v1alpha1
kind: NnfContainerProfile
metadata:
  name: sample-nnfcontainerprofile
  namespace: nnf-system
data:
  # Specifies the number of times a container will be retried upon a failure. A
  # new pod is deployed on each retry. Defaults to 6 by kubernetes itself and
  # must be set. A value of 0 disables retries.
  retryLimit: 6

  # Stop any containers after X seconds once a workflow has transitioned to
  # PostRun. Defaults to 0. A value of 0 disables this behavior.
  postRunTimeoutSeconds: 0

  # List of possible filesystems supported by this container profile. These
  # storages are mounted inside of the container. Any non-optional storage must
  # be supplied with the container directive as an argument and must reference
  # a valid jobdw or persistentdw directive's name.
  #
  # Example:
  #   DW jobdw name=my-gfs2 type=gfs2 capacity=50GB
  #   DW container name=my-container profile=nnfcontainerprofile-sample DW_JOB_foo_local_storage=my-gfs2
  storages:
    - name: DW_JOB_foo_local_storage
      optional: false
    - name: DW_PERSISTENT_foo_persistent_storage
      optional: true

  # Template defines the containers that will be created from container profile.
  template:
    spec:
      containers:
        - name: sample-nnfcontainerprofile
          image: alpine:latest
          command:
          - /bin/sh
          - -c
          - "sleep 15 && exit 0"
