apiVersion: nnf.cray.hpe.com/v1alpha1
kind: NnfStorageProfile
metadata:
  name: placeholder
  namespace: nnf-system
data:
  default: true
  lustreStorage: {}
  gfs2Storage: {}
  xfsStorage: {}
  rawStorage: {}

