resources:
- ../top

patches:
# Let the node-manager daemonset mount host dir for /mnt
- path: manager_volumes_patch.yaml
# Arguments for the controller manager that are specific to kind
- path: manager_environment_deploy_patch.yaml
- path: manager_environment_daemonset_patch.yaml
