apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-manager
  namespace: system
spec:
  template:
    spec:
      containers:
        - name: manager
          volumeMounts:
            - mountPath: /mnt
              name: mnt-dir
              mountPropagation: Bidirectional
      volumes:
        - name: mnt-dir
          hostPath:
            path: /mnt

