apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-manager
  namespace: system
spec:
  template:
    spec:
      containers:
        - name: manager
          workingDir: /localdisk
          volumeMounts:
            - mountPath: /mnt/nnf
              name: mock-filesystems
              mountPropagation: Bidirectional
            - mountPath: /localdisk
              name: localdisk
      volumes:
        - name: mock-filesystems
          hostPath:
            path: /mnt/nnf
            type: DirectoryOrCreate
        - name: localdisk
          hostPath:
            type: DirectoryOrCreate
            path: /localdisk

