# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
  - bases/nnf.cray.hpe.com_nnfnodes.yaml
  - bases/nnf.cray.hpe.com_nnfnodestorages.yaml
  - bases/nnf.cray.hpe.com_nnfnodeblockstorages.yaml
  - bases/nnf.cray.hpe.com_nnfstorages.yaml
  - bases/nnf.cray.hpe.com_nnfdatamovements.yaml
  - bases/nnf.cray.hpe.com_nnfdatamovementmanagers.yaml
  - bases/nnf.cray.hpe.com_nnfaccesses.yaml
  - bases/nnf.cray.hpe.com_nnfstorageprofiles.yaml
  - bases/nnf.cray.hpe.com_nnfnodeecdata.yaml
  - bases/nnf.cray.hpe.com_nnfcontainerprofiles.yaml
  - bases/nnf.cray.hpe.com_nnfportmanagers.yaml
  - bases/nnf.cray.hpe.com_nnflustremgts.yaml
  - bases/nnf.cray.hpe.com_nnfdatamovementprofiles.yaml
  - bases/nnf.cray.hpe.com_nnfsystemstorages.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- path: patches/webhook_in_nnfnodes.yaml
#- path: patches/webhook_in_nnfnodestorages.yaml
#- path: patches/webhook_in_nnfstorages.yaml
#- path: patches/webhook_in_nnfdatamovementmanagers.yaml
#- path: patches/webhook_in_nnfdatamovements.yaml
#- path: patches/webhook_in_nnfaccesses.yaml
#- path: patches/webhook_in_nnfstorageprofiles.yaml
#- path: patches/webhook_in_nnfnodeecdata.yaml
#- path: patches/webhook_in_nnfcontainerprofiles.yaml
#- path: patches/webhook_in_nnfportmanagers.yaml
#- path: patches/webhook_in_nnflustremgts.yaml
#- path: patches/webhook_in_nnfdatamovementprofiles.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- path: patches/cainjection_in_nnfnodes.yaml
#- path: patches/cainjection_in_nnfnodestorages.yaml
#- path: patches/cainjection_in_nnfstorages.yaml
#- path: patches/cainjection_in_nnfdatamovementmanagers.yaml
#- path: patches/cainjection_in_nnfdatamovements.yaml
#- path: patches/cainjection_in_nnfaccesses.yaml
#- path: patches/cainjection_in_nnfstorageprofiles.yaml
#- path: patches/cainjection_in_nnfnodeecdata.yaml
#- path: patches/cainjection_in_nnfcontainerprofiles.yaml
#- path: patches/cainjection_in_nnfportmanagers.yaml
#- path: patches/cainjection_in_nnflustremgts.yaml
#- path: patches/cainjection_in_nnfdatamovementprofiles.yaml
#- path: patches/cainjection_in_nnfsystemstorages.yaml
#- path: patches/cainjection_in_nnfnodeblockstorages.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
  - kustomizeconfig.yaml
