apiVersion: nnf.cray.hpe.com/v1alpha8
kind: NnfContainerProfile
metadata:
  name: example-success
data:
  retryLimit: 6
  storages:
    - name: DW_JOB_foo_local_storage
      optional: false
    - name: DW_PERSISTENT_foo_persistent_storage
      optional: true
    - name: DW_GLOBAL_foo_global_lustre
      optional: true
  spec:
    containers:
      - name: example-success
        image: alpine:latest
        command:
          - /bin/sh
          - -c
          - 'sleep 10 && exit 0'
---
apiVersion: nnf.cray.hpe.com/v1alpha8
kind: NnfContainerProfile
metadata:
  name: example-fail
data:
  spec:
    containers:
      - name: example-fail
        image: alpine:latest
        command:
          - /bin/sh
          - -c
          - 'sleep 10 && exit 1'
---
apiVersion: nnf.cray.hpe.com/v1alpha8
kind: NnfContainerProfile
metadata:
  name: example-randomly-fail
data:
  retryLimit: 6
  storages:
    - name: DW_JOB_foo_local_storage
      optional: false
    - name: DW_PERSISTENT_foo_persistent_storage
      optional: true
  spec:
    containers:
      - name: example-randomly-fail
        image: alpine:latest
        command:
          - /bin/sh
          - -c
          - |
            echo "starting..."
            sleep 10
            x=$(($RANDOM % 2))
            echo "exiting: $x"
            exit $x
---
apiVersion: nnf.cray.hpe.com/v1alpha8
kind: NnfContainerProfile
metadata:
  name: example-forever
data:
  postRunTimeoutSeconds: 5
  retryLimit: 6
  storages:
    - name: DW_JOB_foo_local_storage
      optional: false
    - name: DW_PERSISTENT_foo_persistent_storage
      optional: true
  spec:
    containers:
      - name: example-forever
        image: alpine:latest
        command:
          - /bin/sh
          - -c
          - 'while true; do date && sleep 5; done'
---
apiVersion: nnf.cray.hpe.com/v1alpha8
kind: NnfContainerProfile
metadata:
  name: example-forever-nowait
data:
  postRunTimeoutSeconds: 0
  retryLimit: 6
  storages:
    - name: DW_JOB_foo_local_storage
      optional: false
    - name: DW_PERSISTENT_foo_persistent_storage
      optional: true
  spec:
    containers:
      - name: example-forever
        image: alpine:latest
        command:
          - /bin/sh
          - -c
          - 'while true; do date && sleep 5; done'
---
apiVersion: nnf.cray.hpe.com/v1alpha8
kind: NnfContainerProfile
metadata:
  name: example-mpi
data:
  retryLimit: 6
  numPorts: 1
  storages:
    - name: DW_JOB_foo_local_storage
      optional: false
    - name: DW_PERSISTENT_foo_persistent_storage
      optional: true
    - name: DW_GLOBAL_foo_global_lustre
      optional: true
      pvcMode: ReadWriteMany
  mpiSpec:
    launcher:
      containers:
        - name: example-mpi
          image: nnf-mfu:latest
          command:
            - mpirun
            - dcmp
            - '$(DW_JOB_foo_local_storage)/0'
            - '$(DW_JOB_foo_local_storage)/1'
    worker:
      containers:
        - name: example-mpi
          image: nnf-mfu:latest

---
apiVersion: nnf.cray.hpe.com/v1alpha8
kind: NnfContainerProfile
metadata:
  name: example-mpi-fail
data:
  numPorts: 1
  mpiSpec:
    launcher:
      containers:
        - name: example-mpi-fail
          image: nnf-mfu:latest
          command:
            - mpirun
            - /bin/sh
            - -c
            - 'sleep 10 && exit 1'
    worker:
      containers:
        - name: example-mpi-fail
          image: nnf-mfu:latest
---
apiVersion: nnf.cray.hpe.com/v1alpha8
kind: NnfContainerProfile
metadata:
  name: example-mpi-webserver
data:
  retryLimit: 6
  numPorts: 1
  storages:
    - name: DW_JOB_foo_local_storage
      optional: false
    - name: DW_PERSISTENT_foo_persistent_storage
      optional: true
    - name: DW_GLOBAL_foo_global_lustre
      optional: true
      pvcMode: ReadWriteMany
  mpiSpec:
    launcher:
      containers:
        - name: example-mpi-webserver
          image: ghcr.io/nearnodeflash/nnf-container-example:master
          command:
            - mpirun
            - python3
            - -m
            - http.server
            - $(NNF_CONTAINER_PORTS)
    worker:
      containers:
        - name: example-mpi-webserver
          image: ghcr.io/nearnodeflash/nnf-container-example:master
