apiVersion: nnf.cray.hpe.com/v1alpha1
kind: NnfStorageProfile
metadata:
  name: placeholder
  namespace: nnf-system
data:
  default: true
  lustreStorage:
    combinedMgtMdt: false
    mgtCommandlines:
      zpoolCreate: -O canmount=off -o cachefile=none $POOL_NAME $DEVICE_LIST
      mkfs: --mgs --backfstype=$BACKFS $ZVOL_NAME
    mdtCommandlines:
      zpoolCreate: -O canmount=off -o cachefile=none $POOL_NAME $DEVICE_LIST
      mkfs: --mdt --backfstype=$BACKFS --fsname=$FS_NAME --mgsnode=$MGS_NID --index=$INDEX $ZVOL_NAME
    mgtMdtCommandlines:
      zpoolCreate: -O canmount=off -o cachefile=none $POOL_NAME $DEVICE_LIST
      mkfs: --mgs --mdt --backfstype=$BACKFS --fsname=$FS_NAME --index=$INDEX $ZVOL_NAME
    ostCommandlines:
      zpoolCreate: -O canmount=off -o cachefile=none $POOL_NAME $DEVICE_LIST
      mkfs: --ost --backfstype=$BACKFS --fsname=$FS_NAME --mgsnode=$MGS_NID --index=$INDEX $ZVOL_NAME
    ostOptions:
      scale: 5
      colocateComputes: true
    mdtOptions:
      count: 1
    mgtMdtOptions:
      count: 1
    mgtOptions:
      count: 1
  gfs2Storage:
    commandlines:
      pvCreate: $DEVICE
      pvRemove: $DEVICE
      vgCreate: --shared $VG_NAME $DEVICE_LIST
      vgChange:
        lockStart: --lock-start $VG_NAME
        lockStop: --lock-stop $VG_NAME
      vgRemove: $VG_NAME
      lvCreate: --zero n --activate n --extents 100%VG --stripes $DEVICE_NUM --stripesize=32KiB --name $LV_NAME $VG_NAME
      lvChange:
        activate: --activate ys $VG_NAME/$LV_NAME
        deactivate: --activate n $VG_NAME/$LV_NAME
      lvRemove: $VG_NAME
      mkfs: -j2 -p $PROTOCOL -t $CLUSTER_NAME:$LOCK_SPACE $DEVICE
  xfsStorage:
    commandlines:
      pvCreate: $DEVICE
      pvRemove: $DEVICE
      vgCreate: --shared $VG_NAME $DEVICE_LIST
      vgChange:
        lockStart: --lock-start $VG_NAME
        lockStop: --lock-stop $VG_NAME
      vgRemove: $VG_NAME
      lvCreate: --zero n --activate n --extents 100%VG --stripes $DEVICE_NUM --stripesize=32KiB --name $LV_NAME $VG_NAME
      lvChange:
        activate: --activate y $VG_NAME/$LV_NAME
        deactivate: --activate n $VG_NAME/$LV_NAME
      lvRemove: $VG_NAME
      mkfs: $DEVICE
  rawStorage:
    commandlines:
      pvCreate: $DEVICE
      pvRemove: $DEVICE
      vgCreate: --shared $VG_NAME $DEVICE_LIST
      vgChange:
        lockStart: --lock-start $VG_NAME
        lockStop: --lock-stop $VG_NAME
      vgRemove: $VG_NAME
      lvCreate: --zero n --activate n --extents 100%VG --stripes $DEVICE_NUM --stripesize=32KiB --name $LV_NAME $VG_NAME
      lvChange:
        activate: --activate y $VG_NAME/$LV_NAME
        deactivate: --activate n $VG_NAME/$LV_NAME
      lvRemove: $VG_NAME


