apiVersion: nnf.cray.hpe.com/v1alpha1
kind: NnfContainerProfile
metadata:
  name: example-success
data:
  retryLimit: 6
  storages:
    - name: DW_JOB_foo-local-storage
      optional: false
    - name: DW_PERSISTENT_foo-persistent-storage
      optional: true
  template:
    spec:
      containers:
      - name: example-success
        image: alpine:latest
        command:
        - /bin/sh
        - -c
        - "sleep 15 && exit 0"
---
apiVersion: nnf.cray.hpe.com/v1alpha1
kind: NnfContainerProfile
metadata:
  name: example-randomly-fail
data:
  retryLimit: 6
  storages:
    - name: DW_JOB_foo-local-storage
      optional: false
    - name: DW_PERSISTENT_foo-persistent-storage
      optional: true
  template:
    spec:
      containers:
        - name: example-randomly-fail
          image: alpine:latest
          command:
            - /bin/sh
            - -c
            - |
              echo "starting..."
              sleep 30
              x=$(($RANDOM % 2))
              echo "exiting: $x"
              exit $x
---
apiVersion: nnf.cray.hpe.com/v1alpha1
kind: NnfContainerProfile
metadata:
  name: example-forever
data:
  retryLimit: 6
  storages:
    - name: DW_JOB_foo-local-storage
      optional: false
    - name: DW_PERSISTENT_foo-persistent-storage
      optional: true
  template:
    spec:
      containers:
      - name: example-forever
        image: alpine:latest
        command:
        - /bin/sh
        - -c
        - "while true; do date && sleep 5; done"
