apiVersion: nnf.cray.hpe.com/v1alpha1
kind: NnfDataMovementProfile
metadata:
  name: template
  namespace: nnf-system
data:
  default: false
  slots: 8
  maxSlots: 0
  command: ulimit -n 2048 && mpirun --allow-run-as-root --hostfile $HOSTFILE dcp --progress 1 --uid $UID --gid $GID $SRC $DEST
  logStdout: false
  storeStdout: false
  progressIntervalSeconds: 5
  createDestDir: true
