name: RPM Build
on:
  push:
    branches:
      - '*'

jobs:
  rpm_build:
    runs-on: ubuntu-latest
    steps:
      - name: "Build context"
        run: |
          echo "ref is ${{ github.ref }}"
          echo "ref_type is ${{ github.ref_type }}"
          echo "head.sha is ${{ github.event.pull_request.head.sha }}"
          echo "git-version-gen:"
          ./git-version-gen

      - name: checkout
        uses: actions/checkout@v4
      - name: build rpms
        run: |
           pwd
           make build-daemon
           /bin/ls -al rpms
