# Testing with nektos/act:
#   $ act --rm -j rpm_build --container-architecture linux/amd64 --pull=false --bind push
#


name: RPM Build
on:
  push:
    branches:
      - '*'

jobs:
  rpm_build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      if: ${{ !env.ACT }} # skip during local actions testing
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}

    - name: context
      run: |
        echo "ref is ${{ github.ref }}"
        echo "ref_type is ${{ github.ref_type }}"
        echo "head.sha is ${{ github.event.pull_request.head.sha }}"
        echo "git-version-gen: $(./git-version-gen)"
        echo "want go version: $(grep -E '^go ' go.mod)"

    - name: setup go
      # This is needed only because the 'make build-daemon' target will run
      # the 'go fmt' and 'go vet' commands before it starts the docker build.
      if: ${{ env.ACT }} # use during local actions testing
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'

    - name: build rpms
      run: |
         go version
         pwd
         make build-daemon-rpm
         /bin/ls -al rpms

    - name: upload rpms
      if: ${{ !env.ACT }} # skip during local actions testing
      uses: actions/upload-artifact@v4
      with:
         name: nnf-clientmount.rpm
         path: /home/runner/work/nnf-sos/nnf-sos/rpms/*
         if-no-files-found: error

