apiVersion: dws.cray.hpe.com/v1alpha2
kind: DWDirectiveRule
metadata:
  name: nnf
  annotations:
    helm.sh/hook: post-install
spec:
  - command: "jobdw"
    watchStates: Proposal,Setup,PreRun,PostRun,Teardown
    ruleDefs:
      - key: "^type$"
        type: "string"
        pattern: "^(raw|xfs|gfs2|lustre)$"
        isRequired: true
        isValueRequired: true
      - key: "^capacity$"
        type: "string"
        pattern: "^\\d+(KiB|KB|MiB|MB|GiB|GB|TiB|TB)$"
        isRequired: true
        isValueRequired: true
      - key: "^name$"
        type: "string"
        pattern: "^[a-z][a-z0-9-]+$"
        isRequired: true
        isValueRequired: true
        uniqueWithin: "jobdw_name"
      - key: "^profile$"
        type: "string"
        pattern: "^[a-z][a-z0-9-]+$"
        isRequired: false
        isValueRequired: true
  - command: "create_persistent"
    watchStates: Proposal,Setup,Teardown
    ruleDefs:
      - key: "^type$"
        type: "string"
        pattern: "^(raw|xfs|gfs2|lustre)$"
        isRequired: true
        isValueRequired: true
      - key: "^capacity$"
        type: "string"
        pattern: "^\\d+(KiB|KB|MiB|MB|GiB|GB|TiB|TB)$"
        isRequired: true
        isValueRequired: true
      - key: "^name$"
        type: "string"
        pattern: "^[a-z][a-z0-9-]+$"
        isRequired: true
        isValueRequired: true
        uniqueWithin: "create_persistent_name"
      - key: "^profile$"
        type: "string"
        pattern: "^[a-z][a-z0-9-]+$"
        isRequired: false
        isValueRequired: true
  - command: "destroy_persistent"
    watchStates: Proposal,Teardown
    ruleDefs:
      - key: "^name$"
        type: "string"
        pattern: "^[a-z][a-z0-9-]+$"
        isRequired: true
        isValueRequired: true
        uniqueWithin: "destroy_persistent_name"
  - command: "persistentdw"
    watchStates: Proposal,Setup,PreRun,PostRun,Teardown
    ruleDefs:
      - key: "^name$"
        type: "string"
        pattern: "^[a-z][a-z0-9-]+$"
        isRequired: true
        isValueRequired: true
  - command: "copy_in"
    watchStates: Proposal,DataIn,Teardown
    ruleDefs:
      - key: "^source$"
        type: "string"
        isRequired: true
        isValueRequired: true
      - key: "^destination$"
        type: "string"
        isRequired: true
        isValueRequired: true
  - command: "copy_out"
    watchStates: Proposal,DataOut,Teardown
    ruleDefs:
      - key: "^source$"
        type: "string"
        isRequired: true
        isValueRequired: true
      - key: "^destination$"
        type: "string"
        isRequired: true
        isValueRequired: true
  - command: "container"
    watchStates: Proposal,PreRun,PostRun,Teardown
    ruleDefs:
      - key: "^name$"
        type: "string"
        pattern: "^[a-z][a-z0-9-]+$"
        isRequired: true
        isValueRequired: true
      - key: "^profile$"
        type: "string"
        pattern: "^[a-z][a-z0-9-]+$"
        isRequired: true
        isValueRequired: true
      - key: '^(DW_JOB_|DW_PERSISTENT_)[a-z][a-z0-9_]+$'
        type: "string"
        isRequired: false
        isValueRequired: true
